# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pynq-z2_v1.0.xdc/PYNQ-Z2 v1.0.xdc

# IP: ip/AXI4_TO_AXI4Lite_IP/AXI4_TO_AXI4Lite_IP.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI4_TO_AXI4Lite_IP || ORIG_REF_NAME==AXI4_TO_AXI4Lite_IP} -quiet] -quiet
