# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pynq-z2_v1.0.xdc/PYNQ-Z2 v1.0.xdc

# Block Designs: bd/TOP/TOP.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP || ORIG_REF_NAME==TOP} -quiet] -quiet

# IP: bd/TOP/ip/TOP_clk_wiz_0_0/TOP_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_clk_wiz_0_0 || ORIG_REF_NAME==TOP_clk_wiz_0_0} -quiet] -quiet

# IP: bd/TOP/ip/TOP_axi_uartlite_0_0/TOP_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_axi_uartlite_0_0 || ORIG_REF_NAME==TOP_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/TOP/ip/TOP_axi_gpio_0_0/TOP_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_axi_gpio_0_0 || ORIG_REF_NAME==TOP_axi_gpio_0_0} -quiet] -quiet

# IP: bd/TOP/ip/TOP_axi_interconnect_upgraded_ipi_imp_xbar_0/TOP_axi_interconnect_upgraded_ipi_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_axi_interconnect_upgraded_ipi_imp_xbar_0 || ORIG_REF_NAME==TOP_axi_interconnect_upgraded_ipi_imp_xbar_0} -quiet] -quiet

# IP: bd/TOP/ip/TOP_axi_interconnect_0_0/TOP_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_axi_interconnect_0_0 || ORIG_REF_NAME==TOP_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/TOP/ip/TOP_rst_clk_wiz_0_100M_0/TOP_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==TOP_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/TOP/ip/TOP_FPGA_RVCPU_wrapper_0_0/TOP_FPGA_RVCPU_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_FPGA_RVCPU_wrapper_0_0 || ORIG_REF_NAME==TOP_FPGA_RVCPU_wrapper_0_0} -quiet] -quiet

# IP: bd/TOP/ip/TOP_BRAM_0_0/TOP_BRAM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_BRAM_0_0 || ORIG_REF_NAME==TOP_BRAM_0_0} -quiet] -quiet

# IP: ip/RAM_IP/RAM_IP.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM_IP || ORIG_REF_NAME==RAM_IP} -quiet] -quiet

# IP: bd/TOP/ip/TOP_processing_system7_0_1/TOP_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_processing_system7_0_1 || ORIG_REF_NAME==TOP_processing_system7_0_1} -quiet] -quiet

# IP: bd/TOP/ip/TOP_axi_interconnect_imp_s00_data_fifo_0/TOP_axi_interconnect_imp_s00_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_axi_interconnect_imp_s00_data_fifo_0 || ORIG_REF_NAME==TOP_axi_interconnect_imp_s00_data_fifo_0} -quiet] -quiet

# IP: bd/TOP/ip/TOP_axi_interconnect_imp_m00_data_fifo_0/TOP_axi_interconnect_imp_m00_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_axi_interconnect_imp_m00_data_fifo_0 || ORIG_REF_NAME==TOP_axi_interconnect_imp_m00_data_fifo_0} -quiet] -quiet

# IP: bd/TOP/ip/TOP_axi_interconnect_imp_auto_cc_0/TOP_axi_interconnect_imp_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_axi_interconnect_imp_auto_cc_0 || ORIG_REF_NAME==TOP_axi_interconnect_imp_auto_cc_0} -quiet] -quiet

# IP: bd/TOP/ip/TOP_axi_interconnect_imp_auto_pc_0/TOP_axi_interconnect_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_axi_interconnect_imp_auto_pc_0 || ORIG_REF_NAME==TOP_axi_interconnect_imp_auto_pc_0} -quiet] -quiet

# IP: bd/TOP/ip/TOP_axi_interconnect_imp_auto_pc_1/TOP_axi_interconnect_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_axi_interconnect_imp_auto_pc_1 || ORIG_REF_NAME==TOP_axi_interconnect_imp_auto_pc_1} -quiet] -quiet

# XDC: /home/focused_xy/cs/ysyx/fpga/fpga.gen/sources_1/bd/TOP/TOP_ooc.xdc
