# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/focused_xy/cs/ysyx/fpga/fpga.srcs/sources_1/bd/TOP/ip/TOP_processing_system7_0_1/TOP_processing_system7_0_1.xci
# IP: The module: 'TOP_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/focused_xy/cs/ysyx/fpga/fpga.gen/sources_1/bd/TOP/ip/TOP_processing_system7_0_1/TOP_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'TOP_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/focused_xy/cs/ysyx/fpga/fpga.srcs/sources_1/bd/TOP/ip/TOP_processing_system7_0_1/TOP_processing_system7_0_1.xci
# IP: The module: 'TOP_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/focused_xy/cs/ysyx/fpga/fpga.gen/sources_1/bd/TOP/ip/TOP_processing_system7_0_1/TOP_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'TOP_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
