// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module ICache(	// @[src/main/scala/npc/core/ICache.scala:29:7]
  input         clock,	// @[src/main/scala/npc/core/ICache.scala:29:7]
                reset,	// @[src/main/scala/npc/core/ICache.scala:29:7]
  output        io_in_ready,	// @[src/main/scala/npc/core/ICache.scala:51:14]
  input         io_in_valid,	// @[src/main/scala/npc/core/ICache.scala:51:14]
  input  [31:0] io_in_bits_pc,	// @[src/main/scala/npc/core/ICache.scala:51:14]
  input         io_out_ready,	// @[src/main/scala/npc/core/ICache.scala:51:14]
  output        io_out_valid,	// @[src/main/scala/npc/core/ICache.scala:51:14]
  output [31:0] io_out_bits_pc,	// @[src/main/scala/npc/core/ICache.scala:51:14]
                io_out_bits_instruction,	// @[src/main/scala/npc/core/ICache.scala:51:14]
  input         io_clear,	// @[src/main/scala/npc/core/ICache.scala:51:14]
                io_master_arready,	// @[src/main/scala/npc/core/ICache.scala:51:14]
  output        io_master_arvalid,	// @[src/main/scala/npc/core/ICache.scala:51:14]
  output [31:0] io_master_araddr,	// @[src/main/scala/npc/core/ICache.scala:51:14]
  output        io_master_rready,	// @[src/main/scala/npc/core/ICache.scala:51:14]
  input         io_master_rvalid,	// @[src/main/scala/npc/core/ICache.scala:51:14]
  input  [1:0]  io_master_rresp,	// @[src/main/scala/npc/core/ICache.scala:51:14]
  input  [31:0] io_master_rdata,	// @[src/main/scala/npc/core/ICache.scala:51:14]
  output [7:0]  io_master_arlen,	// @[src/main/scala/npc/core/ICache.scala:51:14]
  input         io_master_rlast	// @[src/main/scala/npc/core/ICache.scala:51:14]
);

  wire        io_out_valid_0;	// @[src/main/scala/npc/core/ICache.scala:166:42]
  wire        isWaitResp;	// @[src/main/scala/npc/core/ICache.scala:68:26]
  reg         cacheBlocksValid_0_0;	// @[src/main/scala/npc/core/ICache.scala:55:65]
  reg         cacheBlocksValid_1_0;	// @[src/main/scala/npc/core/ICache.scala:55:65]
  reg  [25:0] cacheBlocksTag_0_0;	// @[src/main/scala/npc/core/ICache.scala:56:61]
  reg  [25:0] cacheBlocksTag_1_0;	// @[src/main/scala/npc/core/ICache.scala:56:61]
  reg  [31:0] cacheBlocksData_0_0_0;	// @[src/main/scala/npc/core/ICache.scala:57:61]
  reg  [31:0] cacheBlocksData_0_0_1;	// @[src/main/scala/npc/core/ICache.scala:57:61]
  reg  [31:0] cacheBlocksData_0_0_2;	// @[src/main/scala/npc/core/ICache.scala:57:61]
  reg  [31:0] cacheBlocksData_0_0_3;	// @[src/main/scala/npc/core/ICache.scala:57:61]
  reg  [31:0] cacheBlocksData_0_0_4;	// @[src/main/scala/npc/core/ICache.scala:57:61]
  reg  [31:0] cacheBlocksData_0_0_5;	// @[src/main/scala/npc/core/ICache.scala:57:61]
  reg  [31:0] cacheBlocksData_0_0_6;	// @[src/main/scala/npc/core/ICache.scala:57:61]
  reg  [31:0] cacheBlocksData_0_0_7;	// @[src/main/scala/npc/core/ICache.scala:57:61]
  reg  [31:0] cacheBlocksData_1_0_0;	// @[src/main/scala/npc/core/ICache.scala:57:61]
  reg  [31:0] cacheBlocksData_1_0_1;	// @[src/main/scala/npc/core/ICache.scala:57:61]
  reg  [31:0] cacheBlocksData_1_0_2;	// @[src/main/scala/npc/core/ICache.scala:57:61]
  reg  [31:0] cacheBlocksData_1_0_3;	// @[src/main/scala/npc/core/ICache.scala:57:61]
  reg  [31:0] cacheBlocksData_1_0_4;	// @[src/main/scala/npc/core/ICache.scala:57:61]
  reg  [31:0] cacheBlocksData_1_0_5;	// @[src/main/scala/npc/core/ICache.scala:57:61]
  reg  [31:0] cacheBlocksData_1_0_6;	// @[src/main/scala/npc/core/ICache.scala:57:61]
  reg  [31:0] cacheBlocksData_1_0_7;	// @[src/main/scala/npc/core/ICache.scala:57:61]
  wire        rfire = io_master_rvalid & isWaitResp;	// @[src/main/scala/npc/core/ICache.scala:60:33, :68:26]
  reg  [1:0]  state;	// @[src/main/scala/npc/core/ICache.scala:65:27]
  wire        isSetAddr = state == 2'h1;	// @[src/main/scala/npc/core/ICache.scala:65:27, :67:26]
  assign isWaitResp = state == 2'h2;	// @[src/main/scala/npc/core/ICache.scala:65:27, :68:26]
  wire        need = io_in_bits_pc > 32'hEFFFFFF & io_in_bits_pc < 32'hF100000;	// @[src/main/scala/npc/dev/Dev.scala:8:{10,19,27}]
  reg  [31:0] casez_tmp;	// @[src/main/scala/npc/core/ICache.scala:86:30]
  always_comb begin	// @[src/main/scala/npc/core/ICache.scala:86:30]
    casez (io_in_bits_pc[4:2])	// @[src/main/scala/npc/core/ICache.scala:71:43, :86:30]
      3'b000:
        casez_tmp =
          (io_in_bits_pc[5] ? 32'h0 : cacheBlocksData_0_0_0)
          | (io_in_bits_pc[5] ? cacheBlocksData_1_0_0 : 32'h0);	// @[src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/npc/core/ICache.scala:57:61, :72:40, :86:30, :141:21]
      3'b001:
        casez_tmp =
          (io_in_bits_pc[5] ? 32'h0 : cacheBlocksData_0_0_1)
          | (io_in_bits_pc[5] ? cacheBlocksData_1_0_1 : 32'h0);	// @[src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/npc/core/ICache.scala:57:61, :72:40, :86:30, :141:21]
      3'b010:
        casez_tmp =
          (io_in_bits_pc[5] ? 32'h0 : cacheBlocksData_0_0_2)
          | (io_in_bits_pc[5] ? cacheBlocksData_1_0_2 : 32'h0);	// @[src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/npc/core/ICache.scala:57:61, :72:40, :86:30, :141:21]
      3'b011:
        casez_tmp =
          (io_in_bits_pc[5] ? 32'h0 : cacheBlocksData_0_0_3)
          | (io_in_bits_pc[5] ? cacheBlocksData_1_0_3 : 32'h0);	// @[src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/npc/core/ICache.scala:57:61, :72:40, :86:30, :141:21]
      3'b100:
        casez_tmp =
          (io_in_bits_pc[5] ? 32'h0 : cacheBlocksData_0_0_4)
          | (io_in_bits_pc[5] ? cacheBlocksData_1_0_4 : 32'h0);	// @[src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/npc/core/ICache.scala:57:61, :72:40, :86:30, :141:21]
      3'b101:
        casez_tmp =
          (io_in_bits_pc[5] ? 32'h0 : cacheBlocksData_0_0_5)
          | (io_in_bits_pc[5] ? cacheBlocksData_1_0_5 : 32'h0);	// @[src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/npc/core/ICache.scala:57:61, :72:40, :86:30, :141:21]
      3'b110:
        casez_tmp =
          (io_in_bits_pc[5] ? 32'h0 : cacheBlocksData_0_0_6)
          | (io_in_bits_pc[5] ? cacheBlocksData_1_0_6 : 32'h0);	// @[src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/npc/core/ICache.scala:57:61, :72:40, :86:30, :141:21]
      default:
        casez_tmp =
          (io_in_bits_pc[5] ? 32'h0 : cacheBlocksData_0_0_7)
          | (io_in_bits_pc[5] ? cacheBlocksData_1_0_7 : 32'h0);	// @[src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/npc/core/ICache.scala:57:61, :72:40, :86:30, :141:21]
    endcase	// @[src/main/scala/npc/core/ICache.scala:71:43, :86:30]
  end // always_comb
  reg  [3:0]  readCount;	// @[src/main/scala/npc/core/ICache.scala:92:30]
  reg  [31:0] casez_tmp_0;	// @[src/main/scala/npc/core/ICache.scala:118:77]
  always_comb begin	// @[src/main/scala/npc/core/ICache.scala:118:77]
    casez (readCount[2:0])	// @[src/main/scala/npc/core/ICache.scala:92:30, :118:{49,77}]
      3'b000:
        casez_tmp_0 = cacheBlocksData_0_0_0;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
      3'b001:
        casez_tmp_0 = cacheBlocksData_0_0_1;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
      3'b010:
        casez_tmp_0 = cacheBlocksData_0_0_2;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
      3'b011:
        casez_tmp_0 = cacheBlocksData_0_0_3;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
      3'b100:
        casez_tmp_0 = cacheBlocksData_0_0_4;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
      3'b101:
        casez_tmp_0 = cacheBlocksData_0_0_5;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
      3'b110:
        casez_tmp_0 = cacheBlocksData_0_0_6;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
      default:
        casez_tmp_0 = cacheBlocksData_0_0_7;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
    endcase	// @[src/main/scala/npc/core/ICache.scala:92:30, :118:{49,77}]
  end // always_comb
  reg  [31:0] casez_tmp_1;	// @[src/main/scala/npc/core/ICache.scala:118:77]
  always_comb begin	// @[src/main/scala/npc/core/ICache.scala:118:77]
    casez (readCount[2:0])	// @[src/main/scala/npc/core/ICache.scala:92:30, :118:{49,77}]
      3'b000:
        casez_tmp_1 = cacheBlocksData_1_0_0;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
      3'b001:
        casez_tmp_1 = cacheBlocksData_1_0_1;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
      3'b010:
        casez_tmp_1 = cacheBlocksData_1_0_2;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
      3'b011:
        casez_tmp_1 = cacheBlocksData_1_0_3;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
      3'b100:
        casez_tmp_1 = cacheBlocksData_1_0_4;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
      3'b101:
        casez_tmp_1 = cacheBlocksData_1_0_5;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
      3'b110:
        casez_tmp_1 = cacheBlocksData_1_0_6;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
      default:
        casez_tmp_1 = cacheBlocksData_1_0_7;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
    endcase	// @[src/main/scala/npc/core/ICache.scala:92:30, :118:{49,77}]
  end // always_comb
  reg         rdataValid;	// @[src/main/scala/npc/core/ICache.scala:126:27]
  wire        _io_in_ready_T_2 = io_out_ready & io_out_valid_0;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/npc/core/ICache.scala:166:42]
  reg  [31:0] rdataReg;	// @[src/main/scala/npc/core/ICache.scala:128:28]
  wire        dataValid =
    need
      ? ((io_in_bits_pc[5] ? 26'h0 : cacheBlocksTag_0_0)
         | (io_in_bits_pc[5] ? cacheBlocksTag_1_0 : 26'h0)) == io_in_bits_pc[31:6]
        & (~(io_in_bits_pc[5]) & cacheBlocksValid_0_0 | io_in_bits_pc[5]
           & cacheBlocksValid_1_0)
      : rdataValid;	// @[src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/npc/core/ICache.scala:55:65, :56:61, :72:40, :73:21, :78:61, :83:53, :126:27, :129:22, src/main/scala/npc/dev/Dev.scala:8:19]
  assign io_out_valid_0 = io_in_valid & dataValid;	// @[src/main/scala/npc/core/ICache.scala:129:22, :166:42]
  `ifndef SYNTHESIS	// @[src/main/scala/npc/core/ICache.scala:171:11]
    always @(posedge clock) begin	// @[src/main/scala/npc/core/ICache.scala:171:11]
      if (~reset & ~(~rfire | io_master_rresp == 2'h0)) begin	// @[src/main/scala/npc/core/ICache.scala:60:33, :65:27, :171:{11,12,19,38}]
        if (`ASSERT_VERBOSE_COND_)	// @[src/main/scala/npc/core/ICache.scala:171:11]
          $error("Assertion failed\n    at ICache.scala:171 assert(!rfire || io.master.rresp === TransactionResponse.okey.asUInt)\n");	// @[src/main/scala/npc/core/ICache.scala:171:11]
        if (`STOP_COND_)	// @[src/main/scala/npc/core/ICache.scala:171:11]
          $fatal;	// @[src/main/scala/npc/core/ICache.scala:171:11]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire        _state_T_4 = rfire & io_master_rlast;	// @[src/main/scala/npc/core/ICache.scala:60:33, :105:15]
  wire        _cacheBlocksData_1_0_T = rfire & need;	// @[src/main/scala/npc/core/ICache.scala:60:33, :119:15, src/main/scala/npc/dev/Dev.scala:8:19]
  wire        _cacheBlocksData_0_0_T_2 = _cacheBlocksData_1_0_T & ~(io_in_bits_pc[5]);	// @[src/main/scala/npc/core/ICache.scala:72:40, :105:46, :119:{15,23}]
  wire        _cacheBlocksData_1_0_T_2 = _cacheBlocksData_1_0_T & io_in_bits_pc[5];	// @[src/main/scala/npc/core/ICache.scala:72:40, :119:{15,23}]
  always @(posedge clock) begin	// @[src/main/scala/npc/core/ICache.scala:29:7]
    if (reset) begin	// @[src/main/scala/npc/core/ICache.scala:29:7]
      cacheBlocksValid_0_0 <= 1'h0;	// @[src/main/scala/npc/core/ICache.scala:55:65]
      cacheBlocksValid_1_0 <= 1'h0;	// @[src/main/scala/npc/core/ICache.scala:55:65]
      state <= 2'h0;	// @[src/main/scala/npc/core/ICache.scala:65:27]
      readCount <= 4'h0;	// @[src/main/scala/npc/core/ICache.scala:92:30]
      rdataValid <= 1'h0;	// @[src/main/scala/npc/core/ICache.scala:55:65, :126:27]
    end
    else begin	// @[src/main/scala/npc/core/ICache.scala:29:7]
      cacheBlocksValid_0_0 <=
        ~io_clear & (_state_T_4 & need & ~(io_in_bits_pc[5]) | cacheBlocksValid_0_0);	// @[src/main/scala/npc/core/ICache.scala:55:65, :72:40, :105:{15,46}, :109:47, :112:12, :113:34, src/main/scala/npc/dev/Dev.scala:8:19]
      cacheBlocksValid_1_0 <=
        ~io_clear & (_state_T_4 & need & io_in_bits_pc[5] | cacheBlocksValid_1_0);	// @[src/main/scala/npc/core/ICache.scala:55:65, :72:40, :105:15, :109:47, :112:12, :113:34, src/main/scala/npc/dev/Dev.scala:8:19]
      if (state == 2'h2)	// @[src/main/scala/npc/core/ICache.scala:65:27, :68:26, :131:36]
        state <= {~_state_T_4, 1'h0};	// @[src/main/scala/npc/core/ICache.scala:55:65, :65:27, :105:15, :135:23]
      else if (state == 2'h1) begin	// @[src/main/scala/npc/core/ICache.scala:65:27, :67:26, :131:36]
        if (isSetAddr & io_master_arready)	// @[src/main/scala/npc/core/ICache.scala:59:34, :67:26]
          state <= 2'h2;	// @[src/main/scala/npc/core/ICache.scala:65:27, :68:26]
        else	// @[src/main/scala/npc/core/ICache.scala:59:34]
          state <= 2'h1;	// @[src/main/scala/npc/core/ICache.scala:65:27, :67:26]
      end
      else	// @[src/main/scala/npc/core/ICache.scala:131:36]
        state <= {1'h0, ~(|state) & io_in_valid & ~dataValid};	// @[src/main/scala/npc/core/ICache.scala:55:65, :65:27, :66:26, :129:22, :131:36, :133:{20,36}]
      if (|state) begin	// @[src/main/scala/npc/core/ICache.scala:65:27, :66:26]
        if (rfire)	// @[src/main/scala/npc/core/ICache.scala:60:33]
          readCount <= readCount + 4'h1;	// @[src/main/scala/npc/core/ICache.scala:92:30, :93:33]
      end
      else	// @[src/main/scala/npc/core/ICache.scala:66:26]
        readCount <= 4'h0;	// @[src/main/scala/npc/core/ICache.scala:92:30]
      rdataValid <= ~_io_in_ready_T_2 & (_state_T_4 | rdataValid);	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/npc/core/ICache.scala:105:15, :126:27, :127:{20,46}]
    end
    if (_state_T_4 & need & ~(io_in_bits_pc[5]))	// @[src/main/scala/npc/core/ICache.scala:72:40, :105:{15,32,46}, src/main/scala/npc/dev/Dev.scala:8:19]
      cacheBlocksTag_0_0 <= io_in_bits_pc[31:6];	// @[src/main/scala/npc/core/ICache.scala:56:61, :73:21]
    if (_state_T_4 & need & io_in_bits_pc[5])	// @[src/main/scala/npc/core/ICache.scala:72:40, :105:{15,32}, src/main/scala/npc/dev/Dev.scala:8:19]
      cacheBlocksTag_1_0 <= io_in_bits_pc[31:6];	// @[src/main/scala/npc/core/ICache.scala:56:61, :73:21]
    if (readCount[2:0] == 3'h0) begin	// @[src/main/scala/npc/core/ICache.scala:92:30, :118:{49,71}]
      if (_cacheBlocksData_0_0_T_2)	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_0_0_0 <= io_master_rdata;	// @[src/main/scala/npc/core/ICache.scala:57:61]
      else	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_0_0_0 <= casez_tmp_0;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
      if (_cacheBlocksData_1_0_T_2)	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_1_0_0 <= io_master_rdata;	// @[src/main/scala/npc/core/ICache.scala:57:61]
      else	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_1_0_0 <= casez_tmp_1;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
    end
    if (readCount[2:0] == 3'h1) begin	// @[src/main/scala/npc/core/ICache.scala:92:30, :118:{49,71}]
      if (_cacheBlocksData_0_0_T_2)	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_0_0_1 <= io_master_rdata;	// @[src/main/scala/npc/core/ICache.scala:57:61]
      else	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_0_0_1 <= casez_tmp_0;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
      if (_cacheBlocksData_1_0_T_2)	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_1_0_1 <= io_master_rdata;	// @[src/main/scala/npc/core/ICache.scala:57:61]
      else	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_1_0_1 <= casez_tmp_1;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
    end
    if (readCount[2:0] == 3'h2) begin	// @[src/main/scala/npc/core/ICache.scala:92:30, :118:{49,71}]
      if (_cacheBlocksData_0_0_T_2)	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_0_0_2 <= io_master_rdata;	// @[src/main/scala/npc/core/ICache.scala:57:61]
      else	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_0_0_2 <= casez_tmp_0;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
      if (_cacheBlocksData_1_0_T_2)	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_1_0_2 <= io_master_rdata;	// @[src/main/scala/npc/core/ICache.scala:57:61]
      else	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_1_0_2 <= casez_tmp_1;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
    end
    if (readCount[2:0] == 3'h3) begin	// @[src/main/scala/npc/core/ICache.scala:92:30, :118:{49,71}]
      if (_cacheBlocksData_0_0_T_2)	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_0_0_3 <= io_master_rdata;	// @[src/main/scala/npc/core/ICache.scala:57:61]
      else	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_0_0_3 <= casez_tmp_0;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
      if (_cacheBlocksData_1_0_T_2)	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_1_0_3 <= io_master_rdata;	// @[src/main/scala/npc/core/ICache.scala:57:61]
      else	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_1_0_3 <= casez_tmp_1;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
    end
    if (readCount[2:0] == 3'h4) begin	// @[src/main/scala/npc/core/ICache.scala:92:30, :118:{49,71}]
      if (_cacheBlocksData_0_0_T_2)	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_0_0_4 <= io_master_rdata;	// @[src/main/scala/npc/core/ICache.scala:57:61]
      else	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_0_0_4 <= casez_tmp_0;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
      if (_cacheBlocksData_1_0_T_2)	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_1_0_4 <= io_master_rdata;	// @[src/main/scala/npc/core/ICache.scala:57:61]
      else	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_1_0_4 <= casez_tmp_1;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
    end
    if (readCount[2:0] == 3'h5) begin	// @[src/main/scala/npc/core/ICache.scala:92:30, :118:{49,71}]
      if (_cacheBlocksData_0_0_T_2)	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_0_0_5 <= io_master_rdata;	// @[src/main/scala/npc/core/ICache.scala:57:61]
      else	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_0_0_5 <= casez_tmp_0;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
      if (_cacheBlocksData_1_0_T_2)	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_1_0_5 <= io_master_rdata;	// @[src/main/scala/npc/core/ICache.scala:57:61]
      else	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_1_0_5 <= casez_tmp_1;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
    end
    if (readCount[2:0] == 3'h6) begin	// @[src/main/scala/npc/core/ICache.scala:92:30, :118:{49,71}]
      if (_cacheBlocksData_0_0_T_2)	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_0_0_6 <= io_master_rdata;	// @[src/main/scala/npc/core/ICache.scala:57:61]
      else	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_0_0_6 <= casez_tmp_0;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
      if (_cacheBlocksData_1_0_T_2)	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_1_0_6 <= io_master_rdata;	// @[src/main/scala/npc/core/ICache.scala:57:61]
      else	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_1_0_6 <= casez_tmp_1;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
    end
    if (&(readCount[2:0])) begin	// @[src/main/scala/npc/core/ICache.scala:92:30, :118:{49,71}]
      if (_cacheBlocksData_0_0_T_2)	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_0_0_7 <= io_master_rdata;	// @[src/main/scala/npc/core/ICache.scala:57:61]
      else	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_0_0_7 <= casez_tmp_0;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
      if (_cacheBlocksData_1_0_T_2)	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_1_0_7 <= io_master_rdata;	// @[src/main/scala/npc/core/ICache.scala:57:61]
      else	// @[src/main/scala/npc/core/ICache.scala:119:23]
        cacheBlocksData_1_0_7 <= casez_tmp_1;	// @[src/main/scala/npc/core/ICache.scala:57:61, :118:77]
    end
    if (_state_T_4)	// @[src/main/scala/npc/core/ICache.scala:105:15]
      rdataReg <= io_master_rdata;	// @[src/main/scala/npc/core/ICache.scala:128:28]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/scala/npc/core/ICache.scala:29:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/scala/npc/core/ICache.scala:29:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/scala/npc/core/ICache.scala:29:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:18];	// @[src/main/scala/npc/core/ICache.scala:29:7]
    initial begin	// @[src/main/scala/npc/core/ICache.scala:29:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/scala/npc/core/ICache.scala:29:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/scala/npc/core/ICache.scala:29:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/scala/npc/core/ICache.scala:29:7]
        for (logic [4:0] i = 5'h0; i < 5'h13; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// @[src/main/scala/npc/core/ICache.scala:29:7]
        end	// @[src/main/scala/npc/core/ICache.scala:29:7]
        cacheBlocksValid_0_0 = _RANDOM[5'h0][0];	// @[src/main/scala/npc/core/ICache.scala:29:7, :55:65]
        cacheBlocksValid_1_0 = _RANDOM[5'h0][1];	// @[src/main/scala/npc/core/ICache.scala:29:7, :55:65]
        cacheBlocksTag_0_0 = _RANDOM[5'h0][27:2];	// @[src/main/scala/npc/core/ICache.scala:29:7, :55:65, :56:61]
        cacheBlocksTag_1_0 = {_RANDOM[5'h0][31:28], _RANDOM[5'h1][21:0]};	// @[src/main/scala/npc/core/ICache.scala:29:7, :55:65, :56:61]
        cacheBlocksData_0_0_0 = {_RANDOM[5'h1][31:22], _RANDOM[5'h2][21:0]};	// @[src/main/scala/npc/core/ICache.scala:29:7, :56:61, :57:61]
        cacheBlocksData_0_0_1 = {_RANDOM[5'h2][31:22], _RANDOM[5'h3][21:0]};	// @[src/main/scala/npc/core/ICache.scala:29:7, :57:61]
        cacheBlocksData_0_0_2 = {_RANDOM[5'h3][31:22], _RANDOM[5'h4][21:0]};	// @[src/main/scala/npc/core/ICache.scala:29:7, :57:61]
        cacheBlocksData_0_0_3 = {_RANDOM[5'h4][31:22], _RANDOM[5'h5][21:0]};	// @[src/main/scala/npc/core/ICache.scala:29:7, :57:61]
        cacheBlocksData_0_0_4 = {_RANDOM[5'h5][31:22], _RANDOM[5'h6][21:0]};	// @[src/main/scala/npc/core/ICache.scala:29:7, :57:61]
        cacheBlocksData_0_0_5 = {_RANDOM[5'h6][31:22], _RANDOM[5'h7][21:0]};	// @[src/main/scala/npc/core/ICache.scala:29:7, :57:61]
        cacheBlocksData_0_0_6 = {_RANDOM[5'h7][31:22], _RANDOM[5'h8][21:0]};	// @[src/main/scala/npc/core/ICache.scala:29:7, :57:61]
        cacheBlocksData_0_0_7 = {_RANDOM[5'h8][31:22], _RANDOM[5'h9][21:0]};	// @[src/main/scala/npc/core/ICache.scala:29:7, :57:61]
        cacheBlocksData_1_0_0 = {_RANDOM[5'h9][31:22], _RANDOM[5'hA][21:0]};	// @[src/main/scala/npc/core/ICache.scala:29:7, :57:61]
        cacheBlocksData_1_0_1 = {_RANDOM[5'hA][31:22], _RANDOM[5'hB][21:0]};	// @[src/main/scala/npc/core/ICache.scala:29:7, :57:61]
        cacheBlocksData_1_0_2 = {_RANDOM[5'hB][31:22], _RANDOM[5'hC][21:0]};	// @[src/main/scala/npc/core/ICache.scala:29:7, :57:61]
        cacheBlocksData_1_0_3 = {_RANDOM[5'hC][31:22], _RANDOM[5'hD][21:0]};	// @[src/main/scala/npc/core/ICache.scala:29:7, :57:61]
        cacheBlocksData_1_0_4 = {_RANDOM[5'hD][31:22], _RANDOM[5'hE][21:0]};	// @[src/main/scala/npc/core/ICache.scala:29:7, :57:61]
        cacheBlocksData_1_0_5 = {_RANDOM[5'hE][31:22], _RANDOM[5'hF][21:0]};	// @[src/main/scala/npc/core/ICache.scala:29:7, :57:61]
        cacheBlocksData_1_0_6 = {_RANDOM[5'hF][31:22], _RANDOM[5'h10][21:0]};	// @[src/main/scala/npc/core/ICache.scala:29:7, :57:61]
        cacheBlocksData_1_0_7 = {_RANDOM[5'h10][31:22], _RANDOM[5'h11][21:0]};	// @[src/main/scala/npc/core/ICache.scala:29:7, :57:61]
        state = _RANDOM[5'h11][23:22];	// @[src/main/scala/npc/core/ICache.scala:29:7, :57:61, :65:27]
        readCount = _RANDOM[5'h11][28:25];	// @[src/main/scala/npc/core/ICache.scala:29:7, :57:61, :92:30]
        rdataValid = _RANDOM[5'h11][29];	// @[src/main/scala/npc/core/ICache.scala:29:7, :57:61, :126:27]
        rdataReg = {_RANDOM[5'h11][31:30], _RANDOM[5'h12][29:0]};	// @[src/main/scala/npc/core/ICache.scala:29:7, :57:61, :128:28]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/scala/npc/core/ICache.scala:29:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/scala/npc/core/ICache.scala:29:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_ready = ~(|state) & ~io_in_valid | _io_in_ready_T_2;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/npc/core/ICache.scala:29:7, :65:27, :66:26, :164:{27,30,44}]
  assign io_out_valid = io_out_valid_0;	// @[src/main/scala/npc/core/ICache.scala:29:7, :166:42]
  assign io_out_bits_pc = io_in_bits_pc;	// @[src/main/scala/npc/core/ICache.scala:29:7]
  assign io_out_bits_instruction = need ? casez_tmp : rdataReg;	// @[src/main/scala/npc/core/ICache.scala:29:7, :86:30, :128:28, :168:33, src/main/scala/npc/dev/Dev.scala:8:19]
  assign io_master_arvalid = isSetAddr;	// @[src/main/scala/npc/core/ICache.scala:29:7, :67:26]
  assign io_master_araddr = need ? {io_in_bits_pc[31:5], 5'h0} : io_in_bits_pc;	// @[src/main/scala/npc/core/ICache.scala:29:7, :155:{27,39,62}, src/main/scala/npc/dev/Dev.scala:8:19]
  assign io_master_rready = isWaitResp;	// @[src/main/scala/npc/core/ICache.scala:29:7, :68:26]
  assign io_master_arlen = {5'h0, {3{need}}};	// @[src/main/scala/npc/core/ICache.scala:29:7, :158:{21,27}, src/main/scala/npc/dev/Dev.scala:8:19]
endmodule

