# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/focused_xy/cs/ysyx/fpga/fpga.srcs/sources_1/bd/TOP/ip/TOP_BRAM_0_0/TOP_BRAM_0_0.xci
# IP: The module: 'TOP_BRAM_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/focused_xy/cs/ysyx/fpga/fpga.srcs/sources_1/ip/RAM_IP/RAM_IP.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM_IP || ORIG_REF_NAME==RAM_IP} -quiet] -quiet

# XDC: /home/focused_xy/cs/ysyx/fpga/fpga.gen/sources_1/bd/TOP/ip/TOP_BRAM_0_0/TOP_BRAM_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TOP_BRAM_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/focused_xy/cs/ysyx/fpga/fpga.srcs/sources_1/bd/TOP/ip/TOP_BRAM_0_0/TOP_BRAM_0_0.xci
# IP: The module: 'TOP_BRAM_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/focused_xy/cs/ysyx/fpga/fpga.srcs/sources_1/ip/RAM_IP/RAM_IP.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM_IP || ORIG_REF_NAME==RAM_IP} -quiet] -quiet

# XDC: /home/focused_xy/cs/ysyx/fpga/fpga.gen/sources_1/bd/TOP/ip/TOP_BRAM_0_0/TOP_BRAM_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TOP_BRAM_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
