#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Dec 10 13:55:18 CST 2024
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim sim_behav -key {Behavioral:sim_1:Functional:sim} -tclbatch sim.tcl -protoinst "protoinst_files/TOP.protoinst" -log simulate.log"
xsim sim_behav -key {Behavioral:sim_1:Functional:sim} -tclbatch sim.tcl -protoinst "protoinst_files/TOP.protoinst" -log simulate.log

