# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/focused_xy/cs/ysyx/fpga/fpga.srcs/sources_1/ip/AXI_UART_IP/AXI_UART_IP.xci
# IP: The module: 'AXI_UART_IP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/focused_xy/cs/ysyx/fpga/fpga.gen/sources_1/ip/AXI_UART_IP/AXI_UART_IP_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_UART_IP'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/focused_xy/cs/ysyx/fpga/fpga.gen/sources_1/ip/AXI_UART_IP/AXI_UART_IP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_UART_IP'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/focused_xy/cs/ysyx/fpga/fpga.gen/sources_1/ip/AXI_UART_IP/AXI_UART_IP.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_UART_IP'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/focused_xy/cs/ysyx/fpga/fpga.srcs/sources_1/ip/AXI_UART_IP/AXI_UART_IP.xci
# IP: The module: 'AXI_UART_IP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/focused_xy/cs/ysyx/fpga/fpga.gen/sources_1/ip/AXI_UART_IP/AXI_UART_IP_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_UART_IP'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/focused_xy/cs/ysyx/fpga/fpga.gen/sources_1/ip/AXI_UART_IP/AXI_UART_IP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_UART_IP'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/focused_xy/cs/ysyx/fpga/fpga.gen/sources_1/ip/AXI_UART_IP/AXI_UART_IP.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_UART_IP'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
