domain_path: /home/focused_xy/cs/ysyx/fpga/fpga.vitis/rvcpu/export/rvcpu/sw/standalone_ps7_cortexa9_0
app_src_dir: /opt/Xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
lang: c
