// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module IDU(	// @[src/main/scala/npc/core/IDU.scala:46:7]
  input         clock,	// @[src/main/scala/npc/core/IDU.scala:46:7]
  output        io_in_ready,	// @[src/main/scala/npc/core/IDU.scala:47:14]
  input         io_in_valid,	// @[src/main/scala/npc/core/IDU.scala:47:14]
  input  [31:0] io_in_bits_pc,	// @[src/main/scala/npc/core/IDU.scala:47:14]
                io_in_bits_instruction,	// @[src/main/scala/npc/core/IDU.scala:47:14]
  input         io_out_ready,	// @[src/main/scala/npc/core/IDU.scala:47:14]
  output        io_out_valid,	// @[src/main/scala/npc/core/IDU.scala:47:14]
  output [31:0] io_out_bits_aluASrc,	// @[src/main/scala/npc/core/IDU.scala:47:14]
                io_out_bits_aluBSrc,	// @[src/main/scala/npc/core/IDU.scala:47:14]
                io_out_bits_jumpASrc,	// @[src/main/scala/npc/core/IDU.scala:47:14]
                io_out_bits_jumpBSrc,	// @[src/main/scala/npc/core/IDU.scala:47:14]
  output [3:0]  io_out_bits_ra1,	// @[src/main/scala/npc/core/IDU.scala:47:14]
                io_out_bits_wa,	// @[src/main/scala/npc/core/IDU.scala:47:14]
  output        io_out_bits_control_regWe,	// @[src/main/scala/npc/core/IDU.scala:47:14]
  output [1:0]  io_out_bits_control_wbSrc,	// @[src/main/scala/npc/core/IDU.scala:47:14]
  output [2:0]  io_out_bits_control_aluSel,	// @[src/main/scala/npc/core/IDU.scala:47:14]
  output        io_out_bits_control_isArith,	// @[src/main/scala/npc/core/IDU.scala:47:14]
                io_out_bits_control_isLeft,	// @[src/main/scala/npc/core/IDU.scala:47:14]
                io_out_bits_control_isUnsigned,	// @[src/main/scala/npc/core/IDU.scala:47:14]
                io_out_bits_control_isSub,	// @[src/main/scala/npc/core/IDU.scala:47:14]
                io_out_bits_control_csrSrc,	// @[src/main/scala/npc/core/IDU.scala:47:14]
  output [2:0]  io_out_bits_control_csrCtr,	// @[src/main/scala/npc/core/IDU.scala:47:14]
                io_out_bits_control_brType,	// @[src/main/scala/npc/core/IDU.scala:47:14]
  output        io_out_bits_control_pcSrc,	// @[src/main/scala/npc/core/IDU.scala:47:14]
                io_out_bits_control_memRen,	// @[src/main/scala/npc/core/IDU.scala:47:14]
                io_out_bits_control_memWen,	// @[src/main/scala/npc/core/IDU.scala:47:14]
  output [2:0]  io_out_bits_control_memOp,	// @[src/main/scala/npc/core/IDU.scala:47:14]
  output [31:0] io_out_bits_pc,	// @[src/main/scala/npc/core/IDU.scala:47:14]
  output        io_out_bits_isEnd,	// @[src/main/scala/npc/core/IDU.scala:47:14]
  input         io_stall,	// @[src/main/scala/npc/core/IDU.scala:47:14]
  output [3:0]  io_RegFileAccess_ra1,	// @[src/main/scala/npc/core/IDU.scala:47:14]
                io_RegFileAccess_ra2,	// @[src/main/scala/npc/core/IDU.scala:47:14]
  input  [31:0] io_RegFileReturn_rd1,	// @[src/main/scala/npc/core/IDU.scala:47:14]
                io_RegFileReturn_rd2,	// @[src/main/scala/npc/core/IDU.scala:47:14]
  output        io_fence_i	// @[src/main/scala/npc/core/IDU.scala:47:14]
);

  wire        io_out_valid_0;	// @[src/main/scala/npc/core/IDU.scala:104:49]
  wire [29:0] control_decodeResult_invInputs = ~(io_in_bits_instruction[31:2]);	// @[src/main/scala/chisel3/util/pla.scala:78:21, src/main/scala/npc/core/IDU.scala:47:14]
  wire [1:0]  _control_decodeResult_andMatrixOutputs_T =
    {control_decodeResult_invInputs[0], control_decodeResult_invInputs[3]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :91:29, :98:53]
  wire [1:0]  _control_decodeResult_andMatrixOutputs_T_1 =
    {control_decodeResult_invInputs[2], control_decodeResult_invInputs[3]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :91:29, :98:53]
  wire [2:0]  _control_decodeResult_andMatrixOutputs_T_4 =
    {io_in_bits_instruction[2],
     control_decodeResult_invInputs[1],
     control_decodeResult_invInputs[2]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [1:0]  _control_decodeResult_andMatrixOutputs_T_5 =
    {io_in_bits_instruction[2], io_in_bits_instruction[4]};	// @[src/main/scala/chisel3/util/pla.scala:90:45, :98:53]
  wire [2:0]  _control_decodeResult_andMatrixOutputs_T_7 =
    {control_decodeResult_invInputs[2],
     io_in_bits_instruction[5],
     control_decodeResult_invInputs[4]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [1:0]  _control_decodeResult_andMatrixOutputs_T_8 =
    {io_in_bits_instruction[3], io_in_bits_instruction[5]};	// @[src/main/scala/chisel3/util/pla.scala:90:45, :98:53]
  wire [3:0]  _control_decodeResult_andMatrixOutputs_T_9 =
    {control_decodeResult_invInputs[0],
     io_in_bits_instruction[4],
     io_in_bits_instruction[5],
     control_decodeResult_invInputs[4]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [2:0]  _control_decodeResult_andMatrixOutputs_T_10 =
    {io_in_bits_instruction[2], io_in_bits_instruction[4], io_in_bits_instruction[5]};	// @[src/main/scala/chisel3/util/pla.scala:90:45, :98:53]
  wire [2:0]  _control_decodeResult_andMatrixOutputs_T_11 =
    {control_decodeResult_invInputs[0],
     control_decodeResult_invInputs[2],
     io_in_bits_instruction[6]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [1:0]  _control_decodeResult_andMatrixOutputs_T_12 =
    {io_in_bits_instruction[4], io_in_bits_instruction[6]};	// @[src/main/scala/chisel3/util/pla.scala:90:45, :98:53]
  wire [8:0]  _control_decodeResult_andMatrixOutputs_T_15 =
    {io_in_bits_instruction[0],
     io_in_bits_instruction[1],
     io_in_bits_instruction[2],
     control_decodeResult_invInputs[2],
     io_in_bits_instruction[5],
     io_in_bits_instruction[6],
     control_decodeResult_invInputs[10],
     control_decodeResult_invInputs[11],
     control_decodeResult_invInputs[12]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [6:0]  _control_decodeResult_andMatrixOutputs_T_16 =
    {io_in_bits_instruction[0],
     io_in_bits_instruction[1],
     io_in_bits_instruction[2],
     io_in_bits_instruction[3],
     control_decodeResult_invInputs[2],
     io_in_bits_instruction[5],
     io_in_bits_instruction[6]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [2:0]  _control_decodeResult_andMatrixOutputs_T_18 =
    {control_decodeResult_invInputs[0],
     io_in_bits_instruction[12],
     control_decodeResult_invInputs[12]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [7:0]  _control_decodeResult_andMatrixOutputs_T_22 =
    {io_in_bits_instruction[0],
     io_in_bits_instruction[1],
     control_decodeResult_invInputs[0],
     control_decodeResult_invInputs[1],
     io_in_bits_instruction[4],
     io_in_bits_instruction[5],
     io_in_bits_instruction[6],
     io_in_bits_instruction[12]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [1:0]  _control_decodeResult_andMatrixOutputs_T_23 =
    {control_decodeResult_invInputs[2], io_in_bits_instruction[13]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [2:0]  _control_decodeResult_andMatrixOutputs_T_25 =
    {control_decodeResult_invInputs[0],
     io_in_bits_instruction[4],
     io_in_bits_instruction[13]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [7:0]  _control_decodeResult_andMatrixOutputs_T_26 =
    {io_in_bits_instruction[0],
     io_in_bits_instruction[1],
     control_decodeResult_invInputs[0],
     control_decodeResult_invInputs[1],
     io_in_bits_instruction[4],
     io_in_bits_instruction[5],
     io_in_bits_instruction[6],
     io_in_bits_instruction[13]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [2:0]  _control_decodeResult_andMatrixOutputs_T_27 =
    {control_decodeResult_invInputs[0],
     io_in_bits_instruction[4],
     io_in_bits_instruction[14]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [7:0]  _control_decodeResult_andMatrixOutputs_T_28 =
    {io_in_bits_instruction[0],
     io_in_bits_instruction[1],
     control_decodeResult_invInputs[0],
     control_decodeResult_invInputs[1],
     control_decodeResult_invInputs[2],
     io_in_bits_instruction[5],
     io_in_bits_instruction[6],
     io_in_bits_instruction[14]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [4:0]  _control_decodeResult_andMatrixOutputs_T_31 =
    {io_in_bits_instruction[4],
     io_in_bits_instruction[6],
     control_decodeResult_invInputs[10],
     control_decodeResult_invInputs[11],
     io_in_bits_instruction[20]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [31:0] _control_decodeResult_andMatrixOutputs_T_33 =
    {io_in_bits_instruction[0],
     io_in_bits_instruction[1],
     control_decodeResult_invInputs[0],
     control_decodeResult_invInputs[1],
     io_in_bits_instruction[4],
     io_in_bits_instruction[5],
     io_in_bits_instruction[6],
     control_decodeResult_invInputs[5],
     control_decodeResult_invInputs[6],
     control_decodeResult_invInputs[7],
     control_decodeResult_invInputs[8],
     control_decodeResult_invInputs[9],
     control_decodeResult_invInputs[10],
     control_decodeResult_invInputs[11],
     control_decodeResult_invInputs[12],
     control_decodeResult_invInputs[13],
     control_decodeResult_invInputs[14],
     control_decodeResult_invInputs[15],
     control_decodeResult_invInputs[16],
     control_decodeResult_invInputs[17],
     control_decodeResult_invInputs[18],
     io_in_bits_instruction[21],
     control_decodeResult_invInputs[20],
     control_decodeResult_invInputs[21],
     control_decodeResult_invInputs[22],
     control_decodeResult_invInputs[23],
     control_decodeResult_invInputs[24],
     control_decodeResult_invInputs[25],
     io_in_bits_instruction[28],
     io_in_bits_instruction[29],
     control_decodeResult_invInputs[28],
     control_decodeResult_invInputs[29]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [1:0]  _control_decodeResult_orMatrixOutputs_T_47 =
    {&{io_in_bits_instruction[0],
       io_in_bits_instruction[1],
       control_decodeResult_invInputs[0],
       control_decodeResult_invInputs[1],
       control_decodeResult_invInputs[2],
       control_decodeResult_invInputs[3],
       control_decodeResult_invInputs[4],
       control_decodeResult_invInputs[11]},
     &{io_in_bits_instruction[0],
       io_in_bits_instruction[1],
       control_decodeResult_invInputs[0],
       control_decodeResult_invInputs[1],
       control_decodeResult_invInputs[2],
       control_decodeResult_invInputs[3],
       control_decodeResult_invInputs[4],
       control_decodeResult_invInputs[10],
       control_decodeResult_invInputs[12]}};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, :114:19]
  wire [2:0]  control_decodeResult_ImmControlField =
    {&_control_decodeResult_andMatrixOutputs_T_8,
     |{&_control_decodeResult_andMatrixOutputs_T_7,
       &_control_decodeResult_andMatrixOutputs_T_11},
     |{&_control_decodeResult_andMatrixOutputs_T_5,
       &_control_decodeResult_andMatrixOutputs_T_11}};	// @[src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala:88:106, src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}]
  wire        imm_isImmI = control_decodeResult_ImmControlField == 3'h0;	// @[src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala:88:106, src/main/scala/chisel3/util/pla.scala:114:36, src/main/scala/npc/core/ImmGen.scala:21:26]
  wire        imm_isImmS = control_decodeResult_ImmControlField == 3'h2;	// @[src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala:88:106, src/main/scala/npc/core/ImmGen.scala:22:26]
  wire        imm_isImmB = control_decodeResult_ImmControlField == 3'h3;	// @[src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala:88:106, src/main/scala/npc/core/ImmGen.scala:23:26]
  wire        imm_isImmU = control_decodeResult_ImmControlField == 3'h1;	// @[src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala:88:106, src/main/scala/npc/core/ImmGen.scala:24:26]
  wire        imm_isImmJ = control_decodeResult_ImmControlField == 3'h4;	// @[src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala:88:106, src/main/scala/npc/core/ImmGen.scala:25:26]
  wire [31:0] imm =
    {io_in_bits_instruction[31],
     imm_isImmU ? io_in_bits_instruction[30:20] : {11{io_in_bits_instruction[31]}},
     imm_isImmU | imm_isImmJ
       ? io_in_bits_instruction[19:12]
       : {8{io_in_bits_instruction[31]}},
     imm_isImmB
       ? io_in_bits_instruction[7]
       : imm_isImmJ
           ? io_in_bits_instruction[20]
           : ~imm_isImmU & io_in_bits_instruction[31],
     imm_isImmU ? 6'h0 : io_in_bits_instruction[30:25],
     imm_isImmI | imm_isImmJ
       ? io_in_bits_instruction[24:21]
       : imm_isImmS | imm_isImmB ? io_in_bits_instruction[11:8] : 4'h0,
     imm_isImmI ? io_in_bits_instruction[20] : imm_isImmS & io_in_bits_instruction[7]};	// @[src/main/scala/npc/core/ImmGen.scala:21:26, :22:26, :23:26, :24:26, :25:26, :27:{23,36,45,58}, :28:{23,31,46,59,67,82}, :29:{23,46}, :30:{23,44,66,89}, :31:{23,31,46,60}, :32:{23,36,50}, :34:65]
  wire        _io_in_ready_T_1 = io_out_ready & io_out_valid_0;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/npc/core/IDU.scala:104:49]
  reg         ifenced;	// @[src/main/scala/npc/core/IDU.scala:71:24]
  reg  [31:0] casez_tmp;	// @[src/main/scala/chisel3/util/Mux.scala:126:16]
  always_comb begin	// @[src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/core/IDU.scala:86:50]
    casez ({|{&_control_decodeResult_andMatrixOutputs_T_4,
              &_control_decodeResult_andMatrixOutputs_T_8},
            |{&_control_decodeResult_andMatrixOutputs_T,
              &_control_decodeResult_andMatrixOutputs_T_1,
              &_control_decodeResult_andMatrixOutputs_T_5,
              &_control_decodeResult_andMatrixOutputs_T_7,
              &_control_decodeResult_andMatrixOutputs_T_12}})	// @[src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala:88:106, src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}, src/main/scala/npc/core/IDU.scala:86:50]
      2'b00:
        casez_tmp = io_RegFileReturn_rd2;	// @[src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/core/IDU.scala:86:50]
      2'b01:
        casez_tmp = imm;	// @[src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/core/IDU.scala:86:50, src/main/scala/npc/core/ImmGen.scala:34:65]
      2'b10:
        casez_tmp = 32'h4;	// @[src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/core/IDU.scala:86:50]
      default:
        casez_tmp = 32'h0;	// @[src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/core/IDU.scala:69:24, :86:50]
    endcase	// @[src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala:88:106, src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}, src/main/scala/npc/core/IDU.scala:86:50]
  end // always_comb
  assign io_out_valid_0 = io_in_valid & ~io_stall;	// @[src/main/scala/npc/core/IDU.scala:104:{49,52}]
  wire        io_fence_i_0 =
    io_in_valid
    & (&{io_in_bits_instruction[0],
         io_in_bits_instruction[1],
         io_in_bits_instruction[2],
         io_in_bits_instruction[3],
         control_decodeResult_invInputs[2],
         control_decodeResult_invInputs[3],
         control_decodeResult_invInputs[4],
         io_in_bits_instruction[12],
         control_decodeResult_invInputs[11],
         control_decodeResult_invInputs[12]}) & ~ifenced;	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, src/main/scala/npc/core/IDU.scala:71:24, :125:{68,71}]
  always @(posedge clock)	// @[src/main/scala/npc/core/IDU.scala:46:7]
    ifenced <= ~_io_in_ready_T_1 & io_fence_i_0;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/npc/core/IDU.scala:71:{24,25,38}, :125:68]
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/scala/npc/core/IDU.scala:46:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/scala/npc/core/IDU.scala:46:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/scala/npc/core/IDU.scala:46:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[src/main/scala/npc/core/IDU.scala:46:7]
    initial begin	// @[src/main/scala/npc/core/IDU.scala:46:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/scala/npc/core/IDU.scala:46:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/scala/npc/core/IDU.scala:46:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/scala/npc/core/IDU.scala:46:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[src/main/scala/npc/core/IDU.scala:46:7]
        ifenced = _RANDOM[/*Zero width*/ 1'b0][0];	// @[src/main/scala/npc/core/IDU.scala:46:7, :71:24]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/scala/npc/core/IDU.scala:46:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/scala/npc/core/IDU.scala:46:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_ready = ~io_in_valid | _io_in_ready_T_1;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/npc/core/IDU.scala:46:7, :103:{37,50}]
  assign io_out_valid = io_out_valid_0;	// @[src/main/scala/npc/core/IDU.scala:46:7, :104:49]
  assign io_out_bits_aluASrc =
    (|{&{io_in_bits_instruction[0],
         io_in_bits_instruction[1],
         io_in_bits_instruction[2],
         control_decodeResult_invInputs[1],
         io_in_bits_instruction[4],
         control_decodeResult_invInputs[3],
         control_decodeResult_invInputs[4]},
       &_control_decodeResult_andMatrixOutputs_T_15,
       &_control_decodeResult_andMatrixOutputs_T_16})
      ? io_in_bits_pc
      : io_RegFileReturn_rd1;	// @[src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, :114:{19,36}, src/main/scala/npc/core/IDU.scala:46:7]
  assign io_out_bits_aluBSrc = casez_tmp;	// @[src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/core/IDU.scala:46:7]
  assign io_out_bits_jumpASrc =
    (&_control_decodeResult_andMatrixOutputs_T_4) ? io_RegFileReturn_rd1 : io_in_bits_pc;	// @[src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/chisel3/util/pla.scala:98:{53,70}, src/main/scala/npc/core/IDU.scala:46:7]
  assign io_out_bits_jumpBSrc =
    (|{&_control_decodeResult_andMatrixOutputs_T_4,
       &_control_decodeResult_andMatrixOutputs_T_8,
       &_control_decodeResult_andMatrixOutputs_T_11})
      ? imm
      : io_RegFileReturn_rd2;	// @[src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}, src/main/scala/npc/core/IDU.scala:46:7, src/main/scala/npc/core/ImmGen.scala:34:65]
  assign io_out_bits_ra1 = io_in_bits_instruction[18:15];	// @[src/main/scala/npc/core/IDU.scala:46:7, :52:32, :110:34]
  assign io_out_bits_wa = io_in_bits_instruction[10:7];	// @[src/main/scala/npc/core/IDU.scala:46:7, :54:32, :109:34]
  assign io_out_bits_control_regWe =
    |{&_control_decodeResult_andMatrixOutputs_T,
      &_control_decodeResult_andMatrixOutputs_T_1,
      &_control_decodeResult_andMatrixOutputs_T_4,
      &_control_decodeResult_andMatrixOutputs_T_5,
      &_control_decodeResult_andMatrixOutputs_T_8,
      &_control_decodeResult_andMatrixOutputs_T_9,
      &_control_decodeResult_andMatrixOutputs_T_12};	// @[src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}, src/main/scala/npc/core/IDU.scala:46:7]
  assign io_out_bits_control_wbSrc =
    {|{&_control_decodeResult_andMatrixOutputs_T_22,
       &_control_decodeResult_andMatrixOutputs_T_26},
     |_control_decodeResult_orMatrixOutputs_T_47};	// @[src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala:88:106, src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}, src/main/scala/npc/core/IDU.scala:46:7]
  assign io_out_bits_control_aluSel =
    {&_control_decodeResult_andMatrixOutputs_T_27,
     |{&_control_decodeResult_andMatrixOutputs_T_10,
       &_control_decodeResult_andMatrixOutputs_T_11,
       &_control_decodeResult_andMatrixOutputs_T_25},
     |{&_control_decodeResult_andMatrixOutputs_T_10,
       &{control_decodeResult_invInputs[0],
         io_in_bits_instruction[4],
         io_in_bits_instruction[12],
         control_decodeResult_invInputs[11]},
       &{control_decodeResult_invInputs[0],
         control_decodeResult_invInputs[4],
         io_in_bits_instruction[12],
         io_in_bits_instruction[13],
         io_in_bits_instruction[14]}}};	// @[src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala:88:106, src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, :114:{19,36}, src/main/scala/npc/core/IDU.scala:46:7]
  assign io_out_bits_control_isArith = io_in_bits_instruction[30];	// @[src/main/scala/chisel3/util/pla.scala:90:45, src/main/scala/npc/core/IDU.scala:46:7]
  assign io_out_bits_control_isLeft = &_control_decodeResult_andMatrixOutputs_T_18;	// @[src/main/scala/chisel3/util/pla.scala:98:{53,70}, src/main/scala/npc/core/IDU.scala:46:7]
  assign io_out_bits_control_isUnsigned =
    |{&_control_decodeResult_andMatrixOutputs_T_18,
      &_control_decodeResult_andMatrixOutputs_T_23};	// @[src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}, src/main/scala/npc/core/IDU.scala:46:7]
  assign io_out_bits_control_isSub =
    |{&_control_decodeResult_andMatrixOutputs_T_11,
      &_control_decodeResult_andMatrixOutputs_T_25,
      &{io_in_bits_instruction[4],
        io_in_bits_instruction[5],
        io_in_bits_instruction[30]}};	// @[src/main/scala/chisel3/util/pla.scala:90:45, :98:{53,70}, :114:{19,36}, src/main/scala/npc/core/IDU.scala:46:7]
  assign io_out_bits_control_csrSrc = &_control_decodeResult_andMatrixOutputs_T_27;	// @[src/main/scala/chisel3/util/pla.scala:98:{53,70}, src/main/scala/npc/core/IDU.scala:46:7]
  assign io_out_bits_control_csrCtr =
    {|{&{io_in_bits_instruction[0],
         io_in_bits_instruction[1],
         control_decodeResult_invInputs[0],
         control_decodeResult_invInputs[1],
         io_in_bits_instruction[4],
         io_in_bits_instruction[5],
         io_in_bits_instruction[6],
         control_decodeResult_invInputs[5],
         control_decodeResult_invInputs[6],
         control_decodeResult_invInputs[7],
         control_decodeResult_invInputs[8],
         control_decodeResult_invInputs[9],
         control_decodeResult_invInputs[10],
         control_decodeResult_invInputs[11],
         control_decodeResult_invInputs[12],
         control_decodeResult_invInputs[13],
         control_decodeResult_invInputs[14],
         control_decodeResult_invInputs[15],
         control_decodeResult_invInputs[16],
         control_decodeResult_invInputs[17],
         control_decodeResult_invInputs[18],
         control_decodeResult_invInputs[19],
         control_decodeResult_invInputs[20],
         control_decodeResult_invInputs[21],
         control_decodeResult_invInputs[22],
         control_decodeResult_invInputs[23],
         control_decodeResult_invInputs[24],
         control_decodeResult_invInputs[25],
         control_decodeResult_invInputs[26],
         control_decodeResult_invInputs[27],
         control_decodeResult_invInputs[28],
         control_decodeResult_invInputs[29]},
       &_control_decodeResult_andMatrixOutputs_T_33},
     &_control_decodeResult_andMatrixOutputs_T_26,
     |{&_control_decodeResult_andMatrixOutputs_T_22,
       &_control_decodeResult_andMatrixOutputs_T_33}};	// @[src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala:88:106, src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, :114:{19,36}, src/main/scala/npc/core/IDU.scala:46:7]
  assign io_out_bits_control_brType =
    {|{&{io_in_bits_instruction[0],
         io_in_bits_instruction[1],
         control_decodeResult_invInputs[0],
         control_decodeResult_invInputs[1],
         control_decodeResult_invInputs[2],
         io_in_bits_instruction[5],
         io_in_bits_instruction[6],
         control_decodeResult_invInputs[11]},
       &_control_decodeResult_andMatrixOutputs_T_28},
     &_control_decodeResult_andMatrixOutputs_T_28,
     |{&_control_decodeResult_andMatrixOutputs_T_15,
       &_control_decodeResult_andMatrixOutputs_T_16,
       &{io_in_bits_instruction[0],
         io_in_bits_instruction[1],
         control_decodeResult_invInputs[0],
         control_decodeResult_invInputs[1],
         control_decodeResult_invInputs[2],
         io_in_bits_instruction[5],
         io_in_bits_instruction[6],
         io_in_bits_instruction[12],
         control_decodeResult_invInputs[11]},
       &{io_in_bits_instruction[0],
         io_in_bits_instruction[1],
         control_decodeResult_invInputs[0],
         control_decodeResult_invInputs[1],
         control_decodeResult_invInputs[2],
         io_in_bits_instruction[5],
         io_in_bits_instruction[6],
         io_in_bits_instruction[12],
         io_in_bits_instruction[14]}}};	// @[src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala:88:106, src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, :114:{19,36}, src/main/scala/npc/core/IDU.scala:46:7]
  assign io_out_bits_control_pcSrc =
    &{io_in_bits_instruction[4],
      io_in_bits_instruction[6],
      control_decodeResult_invInputs[10],
      control_decodeResult_invInputs[11],
      control_decodeResult_invInputs[18]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, src/main/scala/npc/core/IDU.scala:46:7]
  assign io_out_bits_control_memRen = |_control_decodeResult_orMatrixOutputs_T_47;	// @[src/main/scala/chisel3/util/pla.scala:114:{19,36}, src/main/scala/npc/core/IDU.scala:46:7]
  assign io_out_bits_control_memWen = &_control_decodeResult_andMatrixOutputs_T_7;	// @[src/main/scala/chisel3/util/pla.scala:98:{53,70}, src/main/scala/npc/core/IDU.scala:46:7]
  assign io_out_bits_control_memOp =
    {io_in_bits_instruction[14],
     &_control_decodeResult_andMatrixOutputs_T_23,
     io_in_bits_instruction[12]};	// @[src/main/scala/chisel3/util/experimental/decode/DecoderBundle.scala:88:106, src/main/scala/chisel3/util/pla.scala:90:45, :98:{53,70}, src/main/scala/npc/core/IDU.scala:46:7]
  assign io_out_bits_pc = io_in_bits_pc;	// @[src/main/scala/npc/core/IDU.scala:46:7]
  assign io_out_bits_isEnd = &_control_decodeResult_andMatrixOutputs_T_31;	// @[src/main/scala/chisel3/util/pla.scala:98:{53,70}, src/main/scala/npc/core/IDU.scala:46:7]
  assign io_RegFileAccess_ra1 =
    ((&_control_decodeResult_andMatrixOutputs_T_31)
       ? 4'hA
       : io_in_bits_instruction[18:15])
    & {4{|{&_control_decodeResult_andMatrixOutputs_T,
           &_control_decodeResult_andMatrixOutputs_T_1,
           &_control_decodeResult_andMatrixOutputs_T_4,
           &_control_decodeResult_andMatrixOutputs_T_7,
           &_control_decodeResult_andMatrixOutputs_T_9,
           &_control_decodeResult_andMatrixOutputs_T_11,
           &_control_decodeResult_andMatrixOutputs_T_18,
           &{control_decodeResult_invInputs[0],
             io_in_bits_instruction[13],
             control_decodeResult_invInputs[12]},
           &{io_in_bits_instruction[4],
             io_in_bits_instruction[6],
             control_decodeResult_invInputs[10],
             control_decodeResult_invInputs[11],
             io_in_bits_instruction[21]}}}};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, :114:{19,36}, src/main/scala/npc/core/IDU.scala:46:7, :52:32, :62:{26,32,63,69}]
  assign io_RegFileAccess_ra2 =
    io_in_bits_instruction[23:20]
    & {4{|{&_control_decodeResult_andMatrixOutputs_T_7,
           &_control_decodeResult_andMatrixOutputs_T_9,
           &_control_decodeResult_andMatrixOutputs_T_11}}};	// @[src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}, src/main/scala/npc/core/IDU.scala:46:7, :53:32, :66:{24,31,37}]
  assign io_fence_i = io_fence_i_0;	// @[src/main/scala/npc/core/IDU.scala:46:7, :125:68]
endmodule

