// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module NPC(	// @[src/main/scala/npc/NPC.scala:156:7]
  input clock,	// @[src/main/scala/npc/NPC.scala:156:7]
        reset	// @[src/main/scala/npc/NPC.scala:156:7]
);

  wire        _AXI4Mem_io_awready;	// @[src/main/scala/npc/NPC.scala:160:23]
  wire        _AXI4Mem_io_wready;	// @[src/main/scala/npc/NPC.scala:160:23]
  wire        _AXI4Mem_io_bvalid;	// @[src/main/scala/npc/NPC.scala:160:23]
  wire        _AXI4Mem_io_arready;	// @[src/main/scala/npc/NPC.scala:160:23]
  wire        _AXI4Mem_io_rvalid;	// @[src/main/scala/npc/NPC.scala:160:23]
  wire [31:0] _AXI4Mem_io_rdata;	// @[src/main/scala/npc/NPC.scala:160:23]
  wire        _AXI4Mem_io_rlast;	// @[src/main/scala/npc/NPC.scala:160:23]
  wire        _uart_io_awready;	// @[src/main/scala/npc/NPC.scala:159:23]
  wire        _uart_io_wready;	// @[src/main/scala/npc/NPC.scala:159:23]
  wire        _uart_io_bvalid;	// @[src/main/scala/npc/NPC.scala:159:23]
  wire [1:0]  _uart_io_bresp;	// @[src/main/scala/npc/NPC.scala:159:23]
  wire        _uart_io_arready;	// @[src/main/scala/npc/NPC.scala:159:23]
  wire        _uart_io_rvalid;	// @[src/main/scala/npc/NPC.scala:159:23]
  wire        _npc_io_master_awvalid;	// @[src/main/scala/npc/NPC.scala:158:23]
  wire [31:0] _npc_io_master_awaddr;	// @[src/main/scala/npc/NPC.scala:158:23]
  wire        _npc_io_master_wvalid;	// @[src/main/scala/npc/NPC.scala:158:23]
  wire [31:0] _npc_io_master_wdata;	// @[src/main/scala/npc/NPC.scala:158:23]
  wire [3:0]  _npc_io_master_wstrb;	// @[src/main/scala/npc/NPC.scala:158:23]
  wire        _npc_io_master_bready;	// @[src/main/scala/npc/NPC.scala:158:23]
  wire        _npc_io_master_arvalid;	// @[src/main/scala/npc/NPC.scala:158:23]
  wire [31:0] _npc_io_master_araddr;	// @[src/main/scala/npc/NPC.scala:158:23]
  wire        _npc_io_master_rready;	// @[src/main/scala/npc/NPC.scala:158:23]
  wire [7:0]  _npc_io_master_arlen;	// @[src/main/scala/npc/NPC.scala:158:23]
  reg         writeState;	// @[src/main/scala/npc/axi4/AXI4.scala:381:30]
  reg         readState;	// @[src/main/scala/npc/axi4/AXI4.scala:385:30]
  reg         writeOutSelect;	// @[src/main/scala/npc/axi4/AXI4.scala:429:35]
  reg         readOutSelect;	// @[src/main/scala/npc/axi4/AXI4.scala:432:34]
  wire        _GEN = ~writeOutSelect & writeState;	// @[src/main/scala/npc/axi4/AXI4.scala:381:30, :429:35, :457:{57,65}]
  wire        _GEN_0 = ~readOutSelect & readState;	// @[src/main/scala/npc/axi4/AXI4.scala:385:30, :432:34, :475:{55,63}]
  wire        _GEN_1 = writeOutSelect & writeState;	// @[src/main/scala/npc/axi4/AXI4.scala:381:30, :429:35, :457:65]
  wire        _GEN_2 = _GEN_1 ? _AXI4Mem_io_bvalid : _GEN & _uart_io_bvalid;	// @[src/main/scala/npc/NPC.scala:159:23, :160:23, src/main/scala/npc/axi4/AXI4.scala:449:16, :457:{65,81}, :471:29]
  wire        _GEN_3 = readOutSelect & readState;	// @[src/main/scala/npc/axi4/AXI4.scala:385:30, :432:34, :475:63]
  wire        _GEN_4 = _GEN_3 ? _AXI4Mem_io_rvalid : _GEN_0 & _uart_io_rvalid;	// @[src/main/scala/npc/NPC.scala:159:23, :160:23, src/main/scala/npc/axi4/AXI4.scala:449:16, :475:{63,79}, :484:29]
  wire        rlast = _GEN_3 ? _AXI4Mem_io_rlast : _GEN_0;	// @[src/main/scala/npc/NPC.scala:160:23, src/main/scala/npc/axi4/AXI4.scala:475:{63,79}, :487:29]
  always @(posedge clock) begin	// @[src/main/scala/npc/NPC.scala:156:7]
    if (reset) begin	// @[src/main/scala/npc/NPC.scala:156:7]
      writeState <= 1'h0;	// @[src/main/scala/npc/NPC.scala:156:7, src/main/scala/npc/axi4/AXI4.scala:381:30]
      readState <= 1'h0;	// @[src/main/scala/npc/NPC.scala:156:7, src/main/scala/npc/axi4/AXI4.scala:385:30]
    end
    else begin	// @[src/main/scala/npc/NPC.scala:156:7]
      if (writeState)	// @[src/main/scala/npc/axi4/AXI4.scala:381:30]
        writeState <= ~(_GEN_2 & _npc_io_master_bready);	// @[src/main/scala/npc/NPC.scala:158:23, src/main/scala/npc/axi4/AXI4.scala:381:30, :383:34, :404:46, :437:26, :457:81, :471:29]
      else	// @[src/main/scala/npc/axi4/AXI4.scala:381:30]
        writeState <= _npc_io_master_awvalid;	// @[src/main/scala/npc/NPC.scala:158:23, src/main/scala/npc/axi4/AXI4.scala:381:30]
      if (readState)	// @[src/main/scala/npc/axi4/AXI4.scala:385:30]
        readState <= ~(_GEN_4 & _npc_io_master_rready & rlast);	// @[src/main/scala/npc/NPC.scala:158:23, src/main/scala/npc/axi4/AXI4.scala:381:30, :383:34, :385:30, :444:{26,33}, :475:79, :484:29, :487:29]
      else	// @[src/main/scala/npc/axi4/AXI4.scala:385:30]
        readState <= _npc_io_master_arvalid;	// @[src/main/scala/npc/NPC.scala:158:23, src/main/scala/npc/axi4/AXI4.scala:385:30]
    end
    if (writeState) begin	// @[src/main/scala/npc/axi4/AXI4.scala:381:30]
    end
    else	// @[src/main/scala/npc/axi4/AXI4.scala:381:30]
      writeOutSelect <=
        ~(_npc_io_master_awaddr > 32'hA00003F7 & _npc_io_master_awaddr < 32'hA00003F9);	// @[src/main/scala/npc/NPC.scala:158:23, :164:26, src/main/scala/npc/axi4/AXI4.scala:429:35, src/main/scala/npc/dev/Dev.scala:8:{10,19,27}]
    if (readState) begin	// @[src/main/scala/npc/axi4/AXI4.scala:385:30]
    end
    else	// @[src/main/scala/npc/axi4/AXI4.scala:385:30]
      readOutSelect <=
        ~(_npc_io_master_araddr > 32'hA00003F7 & _npc_io_master_araddr < 32'hA00003F9);	// @[src/main/scala/npc/NPC.scala:158:23, :164:26, src/main/scala/npc/axi4/AXI4.scala:432:34, src/main/scala/npc/dev/Dev.scala:8:{10,19,27}]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/scala/npc/NPC.scala:156:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/scala/npc/NPC.scala:156:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/scala/npc/NPC.scala:156:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[src/main/scala/npc/NPC.scala:156:7]
    initial begin	// @[src/main/scala/npc/NPC.scala:156:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/scala/npc/NPC.scala:156:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/scala/npc/NPC.scala:156:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/scala/npc/NPC.scala:156:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[src/main/scala/npc/NPC.scala:156:7]
        writeState = _RANDOM[/*Zero width*/ 1'b0][0];	// @[src/main/scala/npc/NPC.scala:156:7, src/main/scala/npc/axi4/AXI4.scala:381:30]
        readState = _RANDOM[/*Zero width*/ 1'b0][1];	// @[src/main/scala/npc/NPC.scala:156:7, src/main/scala/npc/axi4/AXI4.scala:381:30, :385:30]
        writeOutSelect = _RANDOM[/*Zero width*/ 1'b0][4];	// @[src/main/scala/npc/NPC.scala:156:7, src/main/scala/npc/axi4/AXI4.scala:381:30, :429:35]
        readOutSelect = _RANDOM[/*Zero width*/ 1'b0][5];	// @[src/main/scala/npc/NPC.scala:156:7, src/main/scala/npc/axi4/AXI4.scala:381:30, :432:34]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/scala/npc/NPC.scala:156:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/scala/npc/NPC.scala:156:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  NPCImpl npc (	// @[src/main/scala/npc/NPC.scala:158:23]
    .clock             (clock),
    .reset             (reset),
    .io_master_awready (_GEN_1 ? _AXI4Mem_io_awready : _GEN & _uart_io_awready),	// @[src/main/scala/npc/NPC.scala:159:23, :160:23, src/main/scala/npc/axi4/AXI4.scala:449:16, :457:{65,81}, :458:29]
    .io_master_awvalid (_npc_io_master_awvalid),
    .io_master_awaddr  (_npc_io_master_awaddr),
    .io_master_wready  (_GEN_1 ? _AXI4Mem_io_wready : _GEN & _uart_io_wready),	// @[src/main/scala/npc/NPC.scala:159:23, :160:23, src/main/scala/npc/axi4/AXI4.scala:449:16, :457:{65,81}, :465:29]
    .io_master_wvalid  (_npc_io_master_wvalid),
    .io_master_wdata   (_npc_io_master_wdata),
    .io_master_wstrb   (_npc_io_master_wstrb),
    .io_master_bready  (_npc_io_master_bready),
    .io_master_bvalid  (_GEN_2),	// @[src/main/scala/npc/axi4/AXI4.scala:457:81, :471:29]
    .io_master_bresp   (_GEN_1 | ~_GEN ? 2'h0 : _uart_io_bresp),	// @[src/main/scala/npc/NPC.scala:158:23, :159:23, :160:23, src/main/scala/npc/axi4/AXI4.scala:457:{65,81}, :472:29]
    .io_master_arready (_GEN_3 ? _AXI4Mem_io_arready : _GEN_0 & _uart_io_arready),	// @[src/main/scala/npc/NPC.scala:159:23, :160:23, src/main/scala/npc/axi4/AXI4.scala:449:16, :475:{63,79}, :476:29]
    .io_master_arvalid (_npc_io_master_arvalid),
    .io_master_araddr  (_npc_io_master_araddr),
    .io_master_rready  (_npc_io_master_rready),
    .io_master_rvalid  (_GEN_4),	// @[src/main/scala/npc/axi4/AXI4.scala:475:79, :484:29]
    .io_master_rresp   (_GEN_3 ? 2'h0 : {_GEN_0, 1'h0}),	// @[src/main/scala/npc/NPC.scala:156:7, :158:23, :160:23, src/main/scala/npc/axi4/AXI4.scala:449:16, :475:{63,79}, :485:29]
    .io_master_rdata   (_GEN_3 ? _AXI4Mem_io_rdata : 32'h0),	// @[src/main/scala/npc/NPC.scala:158:23, :159:23, :160:23, src/main/scala/npc/axi4/AXI4.scala:449:16, :475:{63,79}, :486:29]
    .io_master_arlen   (_npc_io_master_arlen),
    .io_master_rlast   (rlast)	// @[src/main/scala/npc/axi4/AXI4.scala:475:79, :487:29]
  );
  Uart uart (	// @[src/main/scala/npc/NPC.scala:159:23]
    .clock      (clock),
    .reset      (reset),
    .io_awready (_uart_io_awready),
    .io_awvalid (_GEN & _npc_io_master_awvalid),	// @[src/main/scala/npc/NPC.scala:158:23, src/main/scala/npc/axi4/AXI4.scala:452:17, :457:{65,81}, :459:29]
    .io_awaddr  (_GEN ? _npc_io_master_awaddr : 32'h0),	// @[src/main/scala/npc/NPC.scala:158:23, :159:23, src/main/scala/npc/axi4/AXI4.scala:449:16, :452:17, :457:{65,81}, :460:29, :475:79, :486:29]
    .io_wready  (_uart_io_wready),
    .io_wvalid  (_GEN & _npc_io_master_wvalid),	// @[src/main/scala/npc/NPC.scala:158:23, src/main/scala/npc/axi4/AXI4.scala:452:17, :457:{65,81}, :466:29]
    .io_wdata   (_GEN ? _npc_io_master_wdata : 32'h0),	// @[src/main/scala/npc/NPC.scala:158:23, :159:23, src/main/scala/npc/axi4/AXI4.scala:449:16, :452:17, :457:{65,81}, :467:29, :475:79, :486:29]
    .io_wstrb   (_GEN ? _npc_io_master_wstrb : 4'h0),	// @[src/main/scala/npc/NPC.scala:158:23, src/main/scala/npc/axi4/AXI4.scala:83:17, :452:17, :457:{65,81}, :468:29]
    .io_bready  (_GEN & _npc_io_master_bready),	// @[src/main/scala/npc/NPC.scala:158:23, src/main/scala/npc/axi4/AXI4.scala:452:17, :457:{65,81}, :470:29]
    .io_bvalid  (_uart_io_bvalid),
    .io_bresp   (_uart_io_bresp),
    .io_arready (_uart_io_arready),
    .io_arvalid (_GEN_0 & _npc_io_master_arvalid),	// @[src/main/scala/npc/NPC.scala:158:23, src/main/scala/npc/axi4/AXI4.scala:452:17, :475:{63,79}, :477:29]
    .io_araddr  (_GEN_0 ? _npc_io_master_araddr : 32'h0),	// @[src/main/scala/npc/NPC.scala:158:23, :159:23, src/main/scala/npc/axi4/AXI4.scala:449:16, :452:17, :475:{63,79}, :478:29, :486:29]
    .io_rready  (_GEN_0 & _npc_io_master_rready),	// @[src/main/scala/npc/NPC.scala:158:23, src/main/scala/npc/axi4/AXI4.scala:452:17, :475:{63,79}, :483:29]
    .io_rvalid  (_uart_io_rvalid)
  );
  AXI4Mem AXI4Mem (	// @[src/main/scala/npc/NPC.scala:160:23]
    .clock      (clock),
    .reset      (reset),
    .io_awready (_AXI4Mem_io_awready),
    .io_awvalid (_GEN_1 & _npc_io_master_awvalid),	// @[src/main/scala/npc/NPC.scala:158:23, src/main/scala/npc/axi4/AXI4.scala:452:17, :457:{65,81}, :459:29]
    .io_awaddr  (_GEN_1 ? _npc_io_master_awaddr : 32'h0),	// @[src/main/scala/npc/NPC.scala:158:23, :159:23, src/main/scala/npc/axi4/AXI4.scala:449:16, :452:17, :457:{65,81}, :460:29, :475:79, :486:29]
    .io_wready  (_AXI4Mem_io_wready),
    .io_wvalid  (_GEN_1 & _npc_io_master_wvalid),	// @[src/main/scala/npc/NPC.scala:158:23, src/main/scala/npc/axi4/AXI4.scala:452:17, :457:{65,81}, :466:29]
    .io_wdata   (_GEN_1 ? _npc_io_master_wdata : 32'h0),	// @[src/main/scala/npc/NPC.scala:158:23, :159:23, src/main/scala/npc/axi4/AXI4.scala:449:16, :452:17, :457:{65,81}, :467:29, :475:79, :486:29]
    .io_wstrb   (_GEN_1 ? _npc_io_master_wstrb : 4'h0),	// @[src/main/scala/npc/NPC.scala:158:23, src/main/scala/npc/axi4/AXI4.scala:83:17, :452:17, :457:{65,81}, :468:29]
    .io_bready  (_GEN_1 & _npc_io_master_bready),	// @[src/main/scala/npc/NPC.scala:158:23, src/main/scala/npc/axi4/AXI4.scala:452:17, :457:{65,81}, :470:29]
    .io_bvalid  (_AXI4Mem_io_bvalid),
    .io_arready (_AXI4Mem_io_arready),
    .io_arvalid (_GEN_3 & _npc_io_master_arvalid),	// @[src/main/scala/npc/NPC.scala:158:23, src/main/scala/npc/axi4/AXI4.scala:452:17, :475:{63,79}, :477:29]
    .io_araddr  (_GEN_3 ? _npc_io_master_araddr : 32'h0),	// @[src/main/scala/npc/NPC.scala:158:23, :159:23, src/main/scala/npc/axi4/AXI4.scala:449:16, :452:17, :475:{63,79}, :478:29, :486:29]
    .io_rready  (_GEN_3 & _npc_io_master_rready),	// @[src/main/scala/npc/NPC.scala:158:23, src/main/scala/npc/axi4/AXI4.scala:452:17, :475:{63,79}, :483:29]
    .io_rvalid  (_AXI4Mem_io_rvalid),
    .io_rdata   (_AXI4Mem_io_rdata),
    .io_arlen   (_GEN_3 ? _npc_io_master_arlen : 8'h0),	// @[src/main/scala/npc/NPC.scala:158:23, src/main/scala/npc/axi4/AXI4.scala:70:18, :452:17, :475:{63,79}, :480:29]
    .io_rlast   (_AXI4Mem_io_rlast)
  );
endmodule

