// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module NPCImpl(	// @[src/main/scala/npc/NPC.scala:45:7]
  input         clock,	// @[src/main/scala/npc/NPC.scala:45:7]
                reset,	// @[src/main/scala/npc/NPC.scala:45:7]
                io_master_awready,	// @[src/main/scala/npc/NPC.scala:47:14]
  output        io_master_awvalid,	// @[src/main/scala/npc/NPC.scala:47:14]
  output [31:0] io_master_awaddr,	// @[src/main/scala/npc/NPC.scala:47:14]
  input         io_master_wready,	// @[src/main/scala/npc/NPC.scala:47:14]
  output        io_master_wvalid,	// @[src/main/scala/npc/NPC.scala:47:14]
  output [31:0] io_master_wdata,	// @[src/main/scala/npc/NPC.scala:47:14]
  output [3:0]  io_master_wstrb,	// @[src/main/scala/npc/NPC.scala:47:14]
  output        io_master_bready,	// @[src/main/scala/npc/NPC.scala:47:14]
  input         io_master_bvalid,	// @[src/main/scala/npc/NPC.scala:47:14]
  input  [1:0]  io_master_bresp,	// @[src/main/scala/npc/NPC.scala:47:14]
  input         io_master_arready,	// @[src/main/scala/npc/NPC.scala:47:14]
  output        io_master_arvalid,	// @[src/main/scala/npc/NPC.scala:47:14]
  output [31:0] io_master_araddr,	// @[src/main/scala/npc/NPC.scala:47:14]
  output        io_master_rready,	// @[src/main/scala/npc/NPC.scala:47:14]
  input         io_master_rvalid,	// @[src/main/scala/npc/NPC.scala:47:14]
  input  [1:0]  io_master_rresp,	// @[src/main/scala/npc/NPC.scala:47:14]
  input  [31:0] io_master_rdata,	// @[src/main/scala/npc/NPC.scala:47:14]
  output [7:0]  io_master_arlen,	// @[src/main/scala/npc/NPC.scala:47:14]
  input         io_master_rlast	// @[src/main/scala/npc/NPC.scala:47:14]
);

  wire [31:0] _RegFile_io_out_rd1;	// @[src/main/scala/npc/NPC.scala:56:23]
  wire [31:0] _RegFile_io_out_rd2;	// @[src/main/scala/npc/NPC.scala:56:23]
  wire        _WBU_io_in_ready;	// @[src/main/scala/npc/NPC.scala:55:23]
  wire        _WBU_io_out_valid;	// @[src/main/scala/npc/NPC.scala:55:23]
  wire        _WBU_io_out_bits_isEnd;	// @[src/main/scala/npc/NPC.scala:55:23]
  wire [3:0]  _WBU_io_RegFileAccess_wa;	// @[src/main/scala/npc/NPC.scala:55:23]
  wire        _WBU_io_RegFileAccess_we;	// @[src/main/scala/npc/NPC.scala:55:23]
  wire [31:0] _WBU_io_RegFileAccess_wd;	// @[src/main/scala/npc/NPC.scala:55:23]
  wire        _LSU_io_in_ready;	// @[src/main/scala/npc/NPC.scala:54:23]
  wire        _LSU_io_out_valid;	// @[src/main/scala/npc/NPC.scala:54:23]
  wire [3:0]  _LSU_io_out_bits_wa;	// @[src/main/scala/npc/NPC.scala:54:23]
  wire [31:0] _LSU_io_out_bits_wd;	// @[src/main/scala/npc/NPC.scala:54:23]
  wire        _LSU_io_out_bits_control_regWe;	// @[src/main/scala/npc/NPC.scala:54:23]
  wire        _LSU_io_out_bits_isEnd;	// @[src/main/scala/npc/NPC.scala:54:23]
  wire        _LSU_io_master_awvalid;	// @[src/main/scala/npc/NPC.scala:54:23]
  wire [31:0] _LSU_io_master_awaddr;	// @[src/main/scala/npc/NPC.scala:54:23]
  wire        _LSU_io_master_wvalid;	// @[src/main/scala/npc/NPC.scala:54:23]
  wire [31:0] _LSU_io_master_wdata;	// @[src/main/scala/npc/NPC.scala:54:23]
  wire [3:0]  _LSU_io_master_wstrb;	// @[src/main/scala/npc/NPC.scala:54:23]
  wire        _LSU_io_master_bready;	// @[src/main/scala/npc/NPC.scala:54:23]
  wire        _LSU_io_master_arvalid;	// @[src/main/scala/npc/NPC.scala:54:23]
  wire [31:0] _LSU_io_master_araddr;	// @[src/main/scala/npc/NPC.scala:54:23]
  wire        _LSU_io_master_rready;	// @[src/main/scala/npc/NPC.scala:54:23]
  wire [3:0]  _LSU_io_RegFileAccess_wa;	// @[src/main/scala/npc/NPC.scala:54:23]
  wire        _LSU_io_RegFileAccess_we;	// @[src/main/scala/npc/NPC.scala:54:23]
  wire        _EXU_io_in_ready;	// @[src/main/scala/npc/NPC.scala:53:23]
  wire        _EXU_io_out_valid;	// @[src/main/scala/npc/NPC.scala:53:23]
  wire [3:0]  _EXU_io_out_bits_wa;	// @[src/main/scala/npc/NPC.scala:53:23]
  wire [31:0] _EXU_io_out_bits_alu_csr_Out;	// @[src/main/scala/npc/NPC.scala:53:23]
  wire [31:0] _EXU_io_out_bits_wdata;	// @[src/main/scala/npc/NPC.scala:53:23]
  wire        _EXU_io_out_bits_control_regWe;	// @[src/main/scala/npc/NPC.scala:53:23]
  wire        _EXU_io_out_bits_control_wbSrc;	// @[src/main/scala/npc/NPC.scala:53:23]
  wire        _EXU_io_out_bits_control_memRen;	// @[src/main/scala/npc/NPC.scala:53:23]
  wire        _EXU_io_out_bits_control_memWen;	// @[src/main/scala/npc/NPC.scala:53:23]
  wire [2:0]  _EXU_io_out_bits_control_memOp;	// @[src/main/scala/npc/NPC.scala:53:23]
  wire        _EXU_io_out_bits_isEnd;	// @[src/main/scala/npc/NPC.scala:53:23]
  wire        _EXU_io_jump;	// @[src/main/scala/npc/NPC.scala:53:23]
  wire [31:0] _EXU_io_nextPC;	// @[src/main/scala/npc/NPC.scala:53:23]
  wire [3:0]  _EXU_io_RegFileAccess_wa;	// @[src/main/scala/npc/NPC.scala:53:23]
  wire        _EXU_io_RegFileAccess_we;	// @[src/main/scala/npc/NPC.scala:53:23]
  wire        _IDU_io_in_ready;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire        _IDU_io_out_valid;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire [31:0] _IDU_io_out_bits_aluASrc;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire [31:0] _IDU_io_out_bits_aluBSrc;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire [31:0] _IDU_io_out_bits_jumpASrc;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire [31:0] _IDU_io_out_bits_jumpBSrc;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire [3:0]  _IDU_io_out_bits_ra1;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire [3:0]  _IDU_io_out_bits_wa;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire        _IDU_io_out_bits_control_regWe;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire [1:0]  _IDU_io_out_bits_control_wbSrc;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire [2:0]  _IDU_io_out_bits_control_aluSel;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire        _IDU_io_out_bits_control_isArith;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire        _IDU_io_out_bits_control_isLeft;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire        _IDU_io_out_bits_control_isUnsigned;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire        _IDU_io_out_bits_control_isSub;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire        _IDU_io_out_bits_control_csrSrc;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire [2:0]  _IDU_io_out_bits_control_csrCtr;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire [2:0]  _IDU_io_out_bits_control_brType;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire        _IDU_io_out_bits_control_pcSrc;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire        _IDU_io_out_bits_control_memRen;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire        _IDU_io_out_bits_control_memWen;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire [2:0]  _IDU_io_out_bits_control_memOp;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire [31:0] _IDU_io_out_bits_pc;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire        _IDU_io_out_bits_isEnd;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire [3:0]  _IDU_io_RegFileAccess_ra1;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire [3:0]  _IDU_io_RegFileAccess_ra2;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire        _IDU_io_fence_i;	// @[src/main/scala/npc/NPC.scala:52:23]
  wire        _ICache_io_in_ready;	// @[src/main/scala/npc/NPC.scala:51:23]
  wire        _ICache_io_out_valid;	// @[src/main/scala/npc/NPC.scala:51:23]
  wire [31:0] _ICache_io_out_bits_pc;	// @[src/main/scala/npc/NPC.scala:51:23]
  wire [31:0] _ICache_io_out_bits_instruction;	// @[src/main/scala/npc/NPC.scala:51:23]
  wire        _ICache_io_master_arvalid;	// @[src/main/scala/npc/NPC.scala:51:23]
  wire [31:0] _ICache_io_master_araddr;	// @[src/main/scala/npc/NPC.scala:51:23]
  wire        _ICache_io_master_rready;	// @[src/main/scala/npc/NPC.scala:51:23]
  wire [7:0]  _ICache_io_master_arlen;	// @[src/main/scala/npc/NPC.scala:51:23]
  wire [31:0] _IFU_io_out_bits_pc;	// @[src/main/scala/npc/NPC.scala:50:23]
  reg  [31:0] ICache_io_in_bits_r_pc;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg         ICache_io_in_valid_REG;	// @[src/main/scala/npc/NPC.scala:31:47]
  wire        _ICache_io_in_valid_T_6 = ~_EXU_io_jump & ICache_io_in_valid_REG;	// @[src/main/scala/npc/NPC.scala:31:{26,37,47}, :53:23]
  reg  [31:0] IDU_io_in_bits_r_pc;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg  [31:0] IDU_io_in_bits_r_instruction;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg         IDU_io_in_valid_REG;	// @[src/main/scala/npc/NPC.scala:31:47]
  wire        _IDU_io_in_valid_T_6 = ~_EXU_io_jump & IDU_io_in_valid_REG;	// @[src/main/scala/npc/NPC.scala:31:{26,37,47}, :53:23]
  reg  [31:0] EXU_io_in_bits_r_aluASrc;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg  [31:0] EXU_io_in_bits_r_aluBSrc;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg  [31:0] EXU_io_in_bits_r_jumpASrc;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg  [31:0] EXU_io_in_bits_r_jumpBSrc;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg  [3:0]  EXU_io_in_bits_r_ra1;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg  [3:0]  EXU_io_in_bits_r_wa;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg         EXU_io_in_bits_r_control_regWe;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg  [1:0]  EXU_io_in_bits_r_control_wbSrc;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg  [2:0]  EXU_io_in_bits_r_control_aluSel;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg         EXU_io_in_bits_r_control_isArith;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg         EXU_io_in_bits_r_control_isLeft;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg         EXU_io_in_bits_r_control_isUnsigned;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg         EXU_io_in_bits_r_control_isSub;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg         EXU_io_in_bits_r_control_csrSrc;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg  [2:0]  EXU_io_in_bits_r_control_csrCtr;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg  [2:0]  EXU_io_in_bits_r_control_brType;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg         EXU_io_in_bits_r_control_pcSrc;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg         EXU_io_in_bits_r_control_memRen;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg         EXU_io_in_bits_r_control_memWen;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg  [2:0]  EXU_io_in_bits_r_control_memOp;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg  [31:0] EXU_io_in_bits_r_pc;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg         EXU_io_in_bits_r_isEnd;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg         EXU_io_in_valid_REG;	// @[src/main/scala/npc/NPC.scala:29:33]
  reg  [3:0]  LSU_io_in_bits_r_wa;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg  [31:0] LSU_io_in_bits_r_alu_csr_Out;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg  [31:0] LSU_io_in_bits_r_wdata;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg         LSU_io_in_bits_r_control_regWe;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg         LSU_io_in_bits_r_control_wbSrc;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg         LSU_io_in_bits_r_control_memRen;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg         LSU_io_in_bits_r_control_memWen;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg  [2:0]  LSU_io_in_bits_r_control_memOp;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg         LSU_io_in_bits_r_isEnd;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg         LSU_io_in_valid_REG;	// @[src/main/scala/npc/NPC.scala:29:33]
  reg  [3:0]  WBU_io_in_bits_r_wa;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg  [31:0] WBU_io_in_bits_r_wd;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg         WBU_io_in_bits_r_control_regWe;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg         WBU_io_in_bits_r_isEnd;	// @[src/main/scala/npc/NPC.scala:27:33]
  reg         WBU_io_in_valid_REG;	// @[src/main/scala/npc/NPC.scala:29:33]
  wire        isEXURa1RAW =
    _EXU_io_RegFileAccess_we & (|_EXU_io_RegFileAccess_wa)
    & _IDU_io_RegFileAccess_ra1 == _EXU_io_RegFileAccess_wa;	// @[src/main/scala/npc/NPC.scala:52:23, :53:23, :71:{65,73,79}]
  wire        isEXURa2RAW =
    _EXU_io_RegFileAccess_we & (|_EXU_io_RegFileAccess_wa)
    & _IDU_io_RegFileAccess_ra2 == _EXU_io_RegFileAccess_wa;	// @[src/main/scala/npc/NPC.scala:52:23, :53:23, :71:{65,73,79}]
  wire        isEXUForward = ~(EXU_io_in_bits_r_control_wbSrc[0]) & _EXU_io_out_valid;	// @[src/main/scala/npc/NPC.scala:27:33, :53:23, :74:{24,53,57}]
  wire        isLSURa1RAW =
    _LSU_io_RegFileAccess_we & (|_LSU_io_RegFileAccess_wa)
    & _IDU_io_RegFileAccess_ra1 == _LSU_io_RegFileAccess_wa;	// @[src/main/scala/npc/NPC.scala:52:23, :54:23, :71:{65,73,79}]
  wire        isLSURa2RAW =
    _LSU_io_RegFileAccess_we & (|_LSU_io_RegFileAccess_wa)
    & _IDU_io_RegFileAccess_ra2 == _LSU_io_RegFileAccess_wa;	// @[src/main/scala/npc/NPC.scala:52:23, :54:23, :71:{65,73,79}]
  wire        isLSUForward =
    LSU_io_in_bits_r_control_wbSrc ? _LSU_io_out_valid : LSU_io_in_valid_REG;	// @[src/main/scala/npc/NPC.scala:27:33, :29:33, :54:23, :78:27]
  wire        isWBURa1RAW =
    _WBU_io_RegFileAccess_we & (|_WBU_io_RegFileAccess_wa)
    & _IDU_io_RegFileAccess_ra1 == _WBU_io_RegFileAccess_wa;	// @[src/main/scala/npc/NPC.scala:52:23, :55:23, :71:{65,73,79}]
  wire        isWBURa2RAW =
    _WBU_io_RegFileAccess_we & (|_WBU_io_RegFileAccess_wa)
    & _IDU_io_RegFileAccess_ra2 == _WBU_io_RegFileAccess_wa;	// @[src/main/scala/npc/NPC.scala:52:23, :55:23, :71:{65,73,79}]
  reg         writeState;	// @[src/main/scala/npc/axi4/AXI4.scala:384:30]
  reg         readState;	// @[src/main/scala/npc/axi4/AXI4.scala:388:30]
  reg         writeSelectedReg;	// @[src/main/scala/npc/axi4/AXI4.scala:396:37]
  reg         readSelectedReg;	// @[src/main/scala/npc/axi4/AXI4.scala:400:36]
  wire        _GEN = ~writeSelectedReg & writeState;	// @[src/main/scala/npc/axi4/AXI4.scala:384:30, :396:37, :416:29, :460:65]
  wire        _GEN_0 = _GEN & io_master_bvalid;	// @[src/main/scala/npc/axi4/AXI4.scala:452:16, :460:{65,81}, :478:29]
  wire        _GEN_1 = ~readSelectedReg & readState;	// @[src/main/scala/npc/axi4/AXI4.scala:388:30, :400:36, :424:28, :482:63]
  wire        _GEN_2 = _GEN_1 & io_master_rvalid;	// @[src/main/scala/npc/axi4/AXI4.scala:452:16, :482:{63,79}, :495:29]
  wire        _GEN_3 = writeSelectedReg & writeState;	// @[src/main/scala/npc/axi4/AXI4.scala:384:30, :396:37, :460:65]
  wire        _GEN_4 = _GEN_3 | ~_GEN;	// @[src/main/scala/npc/axi4/AXI4.scala:460:{65,81}, :466:30]
  wire        _GEN_5 = readSelectedReg & readState;	// @[src/main/scala/npc/axi4/AXI4.scala:388:30, :400:36, :482:63]
  wire        _GEN_6 = _GEN_5 & io_master_rvalid;	// @[src/main/scala/npc/axi4/AXI4.scala:452:16, :482:{63,79}, :495:29]
  `ifndef SYNTHESIS	// @[src/main/scala/npc/NPC.scala:120:13]
    always @(posedge clock) begin	// @[src/main/scala/npc/NPC.scala:120:13]
      if ((`PRINTF_COND_) & _WBU_io_out_valid & _WBU_io_out_bits_isEnd & ~reset)	// @[src/main/scala/npc/NPC.scala:55:23, :120:13]
        $fwrite(32'h80000002, "SIM END!");	// @[src/main/scala/npc/NPC.scala:120:13]
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire        _IDU_io_in_valid_T_1 = _IDU_io_in_ready & _ICache_io_out_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/npc/NPC.scala:51:23, :52:23]
  wire        _EXU_io_in_valid_T = _EXU_io_in_ready & _IDU_io_out_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/npc/NPC.scala:52:23, :53:23]
  wire        _LSU_io_in_valid_T = _LSU_io_in_ready & _EXU_io_out_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/npc/NPC.scala:53:23, :54:23]
  wire        _WBU_io_in_valid_T = _WBU_io_in_ready & _LSU_io_out_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/npc/NPC.scala:54:23, :55:23]
  always @(posedge clock) begin	// @[src/main/scala/npc/NPC.scala:45:7]
    if (_ICache_io_in_ready)	// @[src/main/scala/npc/NPC.scala:51:23]
      ICache_io_in_bits_r_pc <= _IFU_io_out_bits_pc;	// @[src/main/scala/npc/NPC.scala:27:33, :50:23]
    if (_IDU_io_in_valid_T_1) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      IDU_io_in_bits_r_pc <= _ICache_io_out_bits_pc;	// @[src/main/scala/npc/NPC.scala:27:33, :51:23]
      IDU_io_in_bits_r_instruction <= _ICache_io_out_bits_instruction;	// @[src/main/scala/npc/NPC.scala:27:33, :51:23]
    end
    if (_EXU_io_in_valid_T) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      EXU_io_in_bits_r_aluASrc <= _IDU_io_out_bits_aluASrc;	// @[src/main/scala/npc/NPC.scala:27:33, :52:23]
      EXU_io_in_bits_r_aluBSrc <= _IDU_io_out_bits_aluBSrc;	// @[src/main/scala/npc/NPC.scala:27:33, :52:23]
      EXU_io_in_bits_r_jumpASrc <= _IDU_io_out_bits_jumpASrc;	// @[src/main/scala/npc/NPC.scala:27:33, :52:23]
      EXU_io_in_bits_r_jumpBSrc <= _IDU_io_out_bits_jumpBSrc;	// @[src/main/scala/npc/NPC.scala:27:33, :52:23]
      EXU_io_in_bits_r_ra1 <= _IDU_io_out_bits_ra1;	// @[src/main/scala/npc/NPC.scala:27:33, :52:23]
      EXU_io_in_bits_r_wa <= _IDU_io_out_bits_wa;	// @[src/main/scala/npc/NPC.scala:27:33, :52:23]
      EXU_io_in_bits_r_control_regWe <= _IDU_io_out_bits_control_regWe;	// @[src/main/scala/npc/NPC.scala:27:33, :52:23]
      EXU_io_in_bits_r_control_wbSrc <= _IDU_io_out_bits_control_wbSrc;	// @[src/main/scala/npc/NPC.scala:27:33, :52:23]
      EXU_io_in_bits_r_control_aluSel <= _IDU_io_out_bits_control_aluSel;	// @[src/main/scala/npc/NPC.scala:27:33, :52:23]
      EXU_io_in_bits_r_control_isArith <= _IDU_io_out_bits_control_isArith;	// @[src/main/scala/npc/NPC.scala:27:33, :52:23]
      EXU_io_in_bits_r_control_isLeft <= _IDU_io_out_bits_control_isLeft;	// @[src/main/scala/npc/NPC.scala:27:33, :52:23]
      EXU_io_in_bits_r_control_isUnsigned <= _IDU_io_out_bits_control_isUnsigned;	// @[src/main/scala/npc/NPC.scala:27:33, :52:23]
      EXU_io_in_bits_r_control_isSub <= _IDU_io_out_bits_control_isSub;	// @[src/main/scala/npc/NPC.scala:27:33, :52:23]
      EXU_io_in_bits_r_control_csrSrc <= _IDU_io_out_bits_control_csrSrc;	// @[src/main/scala/npc/NPC.scala:27:33, :52:23]
      EXU_io_in_bits_r_control_csrCtr <= _IDU_io_out_bits_control_csrCtr;	// @[src/main/scala/npc/NPC.scala:27:33, :52:23]
      EXU_io_in_bits_r_control_brType <= _IDU_io_out_bits_control_brType;	// @[src/main/scala/npc/NPC.scala:27:33, :52:23]
      EXU_io_in_bits_r_control_pcSrc <= _IDU_io_out_bits_control_pcSrc;	// @[src/main/scala/npc/NPC.scala:27:33, :52:23]
      EXU_io_in_bits_r_control_memRen <= _IDU_io_out_bits_control_memRen;	// @[src/main/scala/npc/NPC.scala:27:33, :52:23]
      EXU_io_in_bits_r_control_memWen <= _IDU_io_out_bits_control_memWen;	// @[src/main/scala/npc/NPC.scala:27:33, :52:23]
      EXU_io_in_bits_r_control_memOp <= _IDU_io_out_bits_control_memOp;	// @[src/main/scala/npc/NPC.scala:27:33, :52:23]
      EXU_io_in_bits_r_pc <= _IDU_io_out_bits_pc;	// @[src/main/scala/npc/NPC.scala:27:33, :52:23]
      EXU_io_in_bits_r_isEnd <= _IDU_io_out_bits_isEnd;	// @[src/main/scala/npc/NPC.scala:27:33, :52:23]
    end
    if (_LSU_io_in_valid_T) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      LSU_io_in_bits_r_wa <= _EXU_io_out_bits_wa;	// @[src/main/scala/npc/NPC.scala:27:33, :53:23]
      LSU_io_in_bits_r_alu_csr_Out <= _EXU_io_out_bits_alu_csr_Out;	// @[src/main/scala/npc/NPC.scala:27:33, :53:23]
      LSU_io_in_bits_r_wdata <= _EXU_io_out_bits_wdata;	// @[src/main/scala/npc/NPC.scala:27:33, :53:23]
      LSU_io_in_bits_r_control_regWe <= _EXU_io_out_bits_control_regWe;	// @[src/main/scala/npc/NPC.scala:27:33, :53:23]
      LSU_io_in_bits_r_control_wbSrc <= _EXU_io_out_bits_control_wbSrc;	// @[src/main/scala/npc/NPC.scala:27:33, :53:23]
      LSU_io_in_bits_r_control_memRen <= _EXU_io_out_bits_control_memRen;	// @[src/main/scala/npc/NPC.scala:27:33, :53:23]
      LSU_io_in_bits_r_control_memWen <= _EXU_io_out_bits_control_memWen;	// @[src/main/scala/npc/NPC.scala:27:33, :53:23]
      LSU_io_in_bits_r_control_memOp <= _EXU_io_out_bits_control_memOp;	// @[src/main/scala/npc/NPC.scala:27:33, :53:23]
      LSU_io_in_bits_r_isEnd <= _EXU_io_out_bits_isEnd;	// @[src/main/scala/npc/NPC.scala:27:33, :53:23]
    end
    if (_WBU_io_in_valid_T) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      WBU_io_in_bits_r_wa <= _LSU_io_out_bits_wa;	// @[src/main/scala/npc/NPC.scala:27:33, :54:23]
      WBU_io_in_bits_r_wd <= _LSU_io_out_bits_wd;	// @[src/main/scala/npc/NPC.scala:27:33, :54:23]
      WBU_io_in_bits_r_control_regWe <= _LSU_io_out_bits_control_regWe;	// @[src/main/scala/npc/NPC.scala:27:33, :54:23]
      WBU_io_in_bits_r_isEnd <= _LSU_io_out_bits_isEnd;	// @[src/main/scala/npc/NPC.scala:27:33, :54:23]
    end
    if (writeState) begin	// @[src/main/scala/npc/axi4/AXI4.scala:384:30]
    end
    else	// @[src/main/scala/npc/axi4/AXI4.scala:384:30]
      writeSelectedReg <= ~_LSU_io_master_awvalid;	// @[src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/npc/NPC.scala:31:26, :54:23, :102:20, src/main/scala/npc/axi4/AXI4.scala:396:37]
    if (readState) begin	// @[src/main/scala/npc/axi4/AXI4.scala:388:30]
    end
    else	// @[src/main/scala/npc/axi4/AXI4.scala:388:30]
      readSelectedReg <= ~_LSU_io_master_arvalid;	// @[src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/npc/NPC.scala:31:26, :54:23, :102:20, src/main/scala/npc/axi4/AXI4.scala:400:36]
    if (reset) begin	// @[src/main/scala/npc/NPC.scala:45:7]
      ICache_io_in_valid_REG <= 1'h0;	// @[src/main/scala/npc/NPC.scala:31:47, :47:14, :51:23, :52:23, src/main/scala/npc/axi4/AXI4.scala:392:32, :417:36, :418:35, :419:35]
      IDU_io_in_valid_REG <= 1'h0;	// @[src/main/scala/npc/NPC.scala:31:47, :47:14, :51:23, :52:23, src/main/scala/npc/axi4/AXI4.scala:392:32, :417:36, :418:35, :419:35]
      EXU_io_in_valid_REG <= 1'h0;	// @[src/main/scala/npc/NPC.scala:29:33, :47:14, :51:23, :52:23, src/main/scala/npc/axi4/AXI4.scala:392:32, :417:36, :418:35, :419:35]
      LSU_io_in_valid_REG <= 1'h0;	// @[src/main/scala/npc/NPC.scala:29:33, :47:14, :51:23, :52:23, src/main/scala/npc/axi4/AXI4.scala:392:32, :417:36, :418:35, :419:35]
      WBU_io_in_valid_REG <= 1'h0;	// @[src/main/scala/npc/NPC.scala:29:33, :47:14, :51:23, :52:23, src/main/scala/npc/axi4/AXI4.scala:392:32, :417:36, :418:35, :419:35]
      writeState <= 1'h0;	// @[src/main/scala/npc/NPC.scala:47:14, :51:23, :52:23, src/main/scala/npc/axi4/AXI4.scala:384:30, :392:32, :417:36, :418:35, :419:35]
      readState <= 1'h0;	// @[src/main/scala/npc/NPC.scala:47:14, :51:23, :52:23, src/main/scala/npc/axi4/AXI4.scala:388:30, :392:32, :417:36, :418:35, :419:35]
    end
    else begin	// @[src/main/scala/npc/NPC.scala:45:7]
      ICache_io_in_valid_REG <=
        _ICache_io_in_ready | ~_IDU_io_in_valid_T_1 & _ICache_io_in_valid_T_6;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/npc/NPC.scala:31:{37,47,62,66,81}, :51:23]
      IDU_io_in_valid_REG <=
        _IDU_io_in_valid_T_1 | ~_EXU_io_in_valid_T & _IDU_io_in_valid_T_6;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/npc/NPC.scala:31:{37,47,62,66,81}]
      EXU_io_in_valid_REG <=
        _EXU_io_in_valid_T | ~_LSU_io_in_valid_T & EXU_io_in_valid_REG;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/npc/NPC.scala:29:{33,47,51,66}]
      LSU_io_in_valid_REG <=
        _LSU_io_in_valid_T | ~_WBU_io_in_valid_T & LSU_io_in_valid_REG;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/npc/NPC.scala:29:{33,47,51,66}]
      WBU_io_in_valid_REG <=
        _WBU_io_in_valid_T | ~_WBU_io_out_valid & WBU_io_in_valid_REG;	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35, src/main/scala/npc/NPC.scala:29:{33,47,51,66}, :55:23]
      if (writeState)	// @[src/main/scala/npc/axi4/AXI4.scala:384:30]
        writeState <= ~(~writeSelectedReg & _GEN_0 & _LSU_io_master_bready);	// @[src/main/scala/npc/NPC.scala:31:26, :54:23, :102:20, src/main/scala/npc/axi4/AXI4.scala:384:30, :396:37, :416:38, :419:16, :440:26, :452:16, :460:81, :478:29]
      else	// @[src/main/scala/npc/axi4/AXI4.scala:384:30]
        writeState <= _LSU_io_master_awvalid;	// @[src/main/scala/npc/NPC.scala:54:23, src/main/scala/npc/axi4/AXI4.scala:384:30]
      if (readState)	// @[src/main/scala/npc/axi4/AXI4.scala:388:30]
        readState <=
          ~((readSelectedReg
               ? _GEN_6 & _ICache_io_master_rready
               : _GEN_2 & _LSU_io_master_rready) & (readSelectedReg ? _GEN_5 : _GEN_1)
            & io_master_rlast);	// @[src/main/scala/npc/NPC.scala:31:26, :51:23, :54:23, :102:20, src/main/scala/npc/axi4/AXI4.scala:388:30, :400:36, :409:46, :424:37, :426:{16,35}, :427:16, :447:{26,33}, :452:16, :482:{63,79}, :495:29, :498:29]
      else	// @[src/main/scala/npc/axi4/AXI4.scala:388:30]
        readState <= |{_ICache_io_master_arvalid, _LSU_io_master_arvalid};	// @[src/main/scala/npc/NPC.scala:51:23, :54:23, src/main/scala/npc/axi4/AXI4.scala:388:30, :393:62, :401:40]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/scala/npc/NPC.scala:45:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/scala/npc/NPC.scala:45:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/scala/npc/NPC.scala:45:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:33];	// @[src/main/scala/npc/NPC.scala:45:7]
    initial begin	// @[src/main/scala/npc/NPC.scala:45:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/scala/npc/NPC.scala:45:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/scala/npc/NPC.scala:45:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/scala/npc/NPC.scala:45:7]
        for (logic [5:0] i = 6'h0; i < 6'h22; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;	// @[src/main/scala/npc/NPC.scala:45:7]
        end	// @[src/main/scala/npc/NPC.scala:45:7]
        ICache_io_in_bits_r_pc = _RANDOM[6'h0];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        ICache_io_in_valid_REG = _RANDOM[6'h1][0];	// @[src/main/scala/npc/NPC.scala:31:47, :45:7]
        IDU_io_in_bits_r_pc = {_RANDOM[6'h1][31:1], _RANDOM[6'h2][0]};	// @[src/main/scala/npc/NPC.scala:27:33, :31:47, :45:7]
        IDU_io_in_bits_r_instruction = {_RANDOM[6'h2][31:1], _RANDOM[6'h3][0]};	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        IDU_io_in_valid_REG = _RANDOM[6'h5][1];	// @[src/main/scala/npc/NPC.scala:31:47, :45:7]
        EXU_io_in_bits_r_aluASrc = {_RANDOM[6'h5][31:2], _RANDOM[6'h6][1:0]};	// @[src/main/scala/npc/NPC.scala:27:33, :31:47, :45:7]
        EXU_io_in_bits_r_aluBSrc = {_RANDOM[6'h6][31:2], _RANDOM[6'h7][1:0]};	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        EXU_io_in_bits_r_jumpASrc = {_RANDOM[6'h7][31:2], _RANDOM[6'h8][1:0]};	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        EXU_io_in_bits_r_jumpBSrc = {_RANDOM[6'h8][31:2], _RANDOM[6'h9][1:0]};	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        EXU_io_in_bits_r_ra1 = _RANDOM[6'h9][5:2];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        EXU_io_in_bits_r_wa = _RANDOM[6'h9][9:6];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        EXU_io_in_bits_r_control_regWe = _RANDOM[6'h9][10];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        EXU_io_in_bits_r_control_wbSrc = _RANDOM[6'h9][12:11];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        EXU_io_in_bits_r_control_aluSel = _RANDOM[6'h9][15:13];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        EXU_io_in_bits_r_control_isArith = _RANDOM[6'h9][16];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        EXU_io_in_bits_r_control_isLeft = _RANDOM[6'h9][17];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        EXU_io_in_bits_r_control_isUnsigned = _RANDOM[6'h9][18];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        EXU_io_in_bits_r_control_isSub = _RANDOM[6'h9][19];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        EXU_io_in_bits_r_control_csrSrc = _RANDOM[6'h9][20];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        EXU_io_in_bits_r_control_csrCtr = _RANDOM[6'h9][23:21];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        EXU_io_in_bits_r_control_brType = _RANDOM[6'h9][26:24];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        EXU_io_in_bits_r_control_pcSrc = _RANDOM[6'h9][27];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        EXU_io_in_bits_r_control_memRen = _RANDOM[6'h9][28];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        EXU_io_in_bits_r_control_memWen = _RANDOM[6'h9][29];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        EXU_io_in_bits_r_control_memOp = {_RANDOM[6'h9][31:30], _RANDOM[6'hA][0]};	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        EXU_io_in_bits_r_pc = {_RANDOM[6'hA][31:1], _RANDOM[6'hB][0]};	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        EXU_io_in_bits_r_isEnd = _RANDOM[6'hE][1];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        EXU_io_in_valid_REG = _RANDOM[6'hF][2];	// @[src/main/scala/npc/NPC.scala:29:33, :45:7]
        LSU_io_in_bits_r_wa = _RANDOM[6'hF][6:3];	// @[src/main/scala/npc/NPC.scala:27:33, :29:33, :45:7]
        LSU_io_in_bits_r_alu_csr_Out = {_RANDOM[6'hF][31:7], _RANDOM[6'h10][6:0]};	// @[src/main/scala/npc/NPC.scala:27:33, :29:33, :45:7]
        LSU_io_in_bits_r_wdata = {_RANDOM[6'h10][31:7], _RANDOM[6'h11][6:0]};	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        LSU_io_in_bits_r_control_regWe = _RANDOM[6'h11][7];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        LSU_io_in_bits_r_control_wbSrc = _RANDOM[6'h11][8];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        LSU_io_in_bits_r_control_memRen = _RANDOM[6'h11][9];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        LSU_io_in_bits_r_control_memWen = _RANDOM[6'h11][10];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        LSU_io_in_bits_r_control_memOp = _RANDOM[6'h11][13:11];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        LSU_io_in_bits_r_isEnd = _RANDOM[6'h15][14];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        LSU_io_in_valid_REG = _RANDOM[6'h18][15];	// @[src/main/scala/npc/NPC.scala:29:33, :45:7]
        WBU_io_in_bits_r_wa = _RANDOM[6'h18][19:16];	// @[src/main/scala/npc/NPC.scala:27:33, :29:33, :45:7]
        WBU_io_in_bits_r_wd = {_RANDOM[6'h18][31:20], _RANDOM[6'h19][19:0]};	// @[src/main/scala/npc/NPC.scala:27:33, :29:33, :45:7]
        WBU_io_in_bits_r_control_regWe = _RANDOM[6'h19][20];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        WBU_io_in_bits_r_isEnd = _RANDOM[6'h1E][22];	// @[src/main/scala/npc/NPC.scala:27:33, :45:7]
        WBU_io_in_valid_REG = _RANDOM[6'h21][23];	// @[src/main/scala/npc/NPC.scala:29:33, :45:7]
        writeState = _RANDOM[6'h21][24];	// @[src/main/scala/npc/NPC.scala:29:33, :45:7, src/main/scala/npc/axi4/AXI4.scala:384:30]
        readState = _RANDOM[6'h21][25];	// @[src/main/scala/npc/NPC.scala:29:33, :45:7, src/main/scala/npc/axi4/AXI4.scala:388:30]
        writeSelectedReg = _RANDOM[6'h21][26];	// @[src/main/scala/npc/NPC.scala:29:33, :45:7, src/main/scala/npc/axi4/AXI4.scala:396:37]
        readSelectedReg = _RANDOM[6'h21][27];	// @[src/main/scala/npc/NPC.scala:29:33, :45:7, src/main/scala/npc/axi4/AXI4.scala:400:36]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/scala/npc/NPC.scala:45:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/scala/npc/NPC.scala:45:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  IFU IFU (	// @[src/main/scala/npc/NPC.scala:50:23]
    .clock          (clock),
    .reset          (reset),
    .io_out_ready   (_ICache_io_in_ready),	// @[src/main/scala/npc/NPC.scala:51:23]
    .io_out_bits_pc (_IFU_io_out_bits_pc),
    .io_jump        (_EXU_io_jump | _IDU_io_fence_i),	// @[src/main/scala/npc/NPC.scala:52:23, :53:23, :64:32]
    .io_nextPC      (_EXU_io_jump ? _EXU_io_nextPC : ICache_io_in_bits_r_pc)	// @[src/main/scala/npc/NPC.scala:27:33, :53:23, :65:23]
  );
  ICache ICache (	// @[src/main/scala/npc/NPC.scala:51:23]
    .clock                   (clock),
    .reset                   (reset),
    .io_in_ready             (_ICache_io_in_ready),
    .io_in_valid             (_ICache_io_in_valid_T_6),	// @[src/main/scala/npc/NPC.scala:31:37]
    .io_in_bits_pc           (ICache_io_in_bits_r_pc),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_out_ready            (_IDU_io_in_ready),	// @[src/main/scala/npc/NPC.scala:52:23]
    .io_out_valid            (_ICache_io_out_valid),
    .io_out_bits_pc          (_ICache_io_out_bits_pc),
    .io_out_bits_instruction (_ICache_io_out_bits_instruction),
    .io_clear                (_IDU_io_fence_i),	// @[src/main/scala/npc/NPC.scala:52:23]
    .io_master_arready       (_GEN_5 & io_master_arready),	// @[src/main/scala/npc/axi4/AXI4.scala:452:16, :482:{63,79}, :483:29]
    .io_master_arvalid       (_ICache_io_master_arvalid),
    .io_master_araddr        (_ICache_io_master_araddr),
    .io_master_rready        (_ICache_io_master_rready),
    .io_master_rvalid        (_GEN_6),	// @[src/main/scala/npc/axi4/AXI4.scala:452:16, :482:79, :495:29]
    .io_master_rresp         (_GEN_5 ? io_master_rresp : 2'h0),	// @[src/main/scala/npc/axi4/AXI4.scala:82:17, :452:16, :482:{63,79}, :496:29]
    .io_master_rdata         (_GEN_5 ? io_master_rdata : 32'h0),	// @[src/main/scala/npc/NPC.scala:47:14, :51:23, :52:23, :53:23, :54:23, src/main/scala/npc/axi4/AXI4.scala:452:16, :482:{63,79}, :497:29]
    .io_master_arlen         (_ICache_io_master_arlen),
    .io_master_rlast         (_GEN_5 & io_master_rlast)	// @[src/main/scala/npc/axi4/AXI4.scala:452:16, :482:{63,79}, :498:29]
  );
  IDU IDU (	// @[src/main/scala/npc/NPC.scala:52:23]
    .clock                          (clock),
    .io_in_ready                    (_IDU_io_in_ready),
    .io_in_valid                    (_IDU_io_in_valid_T_6),	// @[src/main/scala/npc/NPC.scala:31:37]
    .io_in_bits_pc                  (IDU_io_in_bits_r_pc),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_instruction         (IDU_io_in_bits_r_instruction),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_out_ready                   (_EXU_io_in_ready),	// @[src/main/scala/npc/NPC.scala:53:23]
    .io_out_valid                   (_IDU_io_out_valid),
    .io_out_bits_aluASrc            (_IDU_io_out_bits_aluASrc),
    .io_out_bits_aluBSrc            (_IDU_io_out_bits_aluBSrc),
    .io_out_bits_jumpASrc           (_IDU_io_out_bits_jumpASrc),
    .io_out_bits_jumpBSrc           (_IDU_io_out_bits_jumpBSrc),
    .io_out_bits_ra1                (_IDU_io_out_bits_ra1),
    .io_out_bits_wa                 (_IDU_io_out_bits_wa),
    .io_out_bits_control_regWe      (_IDU_io_out_bits_control_regWe),
    .io_out_bits_control_wbSrc      (_IDU_io_out_bits_control_wbSrc),
    .io_out_bits_control_aluSel     (_IDU_io_out_bits_control_aluSel),
    .io_out_bits_control_isArith    (_IDU_io_out_bits_control_isArith),
    .io_out_bits_control_isLeft     (_IDU_io_out_bits_control_isLeft),
    .io_out_bits_control_isUnsigned (_IDU_io_out_bits_control_isUnsigned),
    .io_out_bits_control_isSub      (_IDU_io_out_bits_control_isSub),
    .io_out_bits_control_csrSrc     (_IDU_io_out_bits_control_csrSrc),
    .io_out_bits_control_csrCtr     (_IDU_io_out_bits_control_csrCtr),
    .io_out_bits_control_brType     (_IDU_io_out_bits_control_brType),
    .io_out_bits_control_pcSrc      (_IDU_io_out_bits_control_pcSrc),
    .io_out_bits_control_memRen     (_IDU_io_out_bits_control_memRen),
    .io_out_bits_control_memWen     (_IDU_io_out_bits_control_memWen),
    .io_out_bits_control_memOp      (_IDU_io_out_bits_control_memOp),
    .io_out_bits_pc                 (_IDU_io_out_bits_pc),
    .io_out_bits_isEnd              (_IDU_io_out_bits_isEnd),
    .io_stall
      ((isEXURa1RAW | isEXURa2RAW) & ~isEXUForward | (isLSURa1RAW | isLSURa2RAW)
       & ~isLSUForward | (isWBURa1RAW | isWBURa2RAW) & ~WBU_io_in_valid_REG),	// @[src/main/scala/npc/NPC.scala:29:33, :71:73, :74:57, :78:27, :100:{33,49,52,84,100,103,118,135,151,154}]
    .io_RegFileAccess_ra1           (_IDU_io_RegFileAccess_ra1),
    .io_RegFileAccess_ra2           (_IDU_io_RegFileAccess_ra2),
    .io_RegFileReturn_rd1
      (isEXURa1RAW & isEXUForward
         ? _EXU_io_out_bits_alu_csr_Out
         : isLSURa1RAW & isLSUForward
             ? _LSU_io_out_bits_wd
             : isWBURa1RAW & WBU_io_in_valid_REG
                 ? _WBU_io_RegFileAccess_wd
                 : _RegFile_io_out_rd1),	// @[src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/NPC.scala:29:33, :53:23, :54:23, :55:23, :56:23, :71:73, :74:57, :78:27, :87:20, :88:20, :89:20]
    .io_RegFileReturn_rd2
      (isEXURa2RAW & isEXUForward
         ? _EXU_io_out_bits_alu_csr_Out
         : isLSURa2RAW & isLSUForward
             ? _LSU_io_out_bits_wd
             : isWBURa2RAW & WBU_io_in_valid_REG
                 ? _WBU_io_RegFileAccess_wd
                 : _RegFile_io_out_rd2),	// @[src/main/scala/chisel3/util/Mux.scala:126:16, src/main/scala/npc/NPC.scala:29:33, :53:23, :54:23, :55:23, :56:23, :71:73, :74:57, :78:27, :95:20, :96:20, :97:20]
    .io_fence_i                     (_IDU_io_fence_i)
  );
  EXU EXU (	// @[src/main/scala/npc/NPC.scala:53:23]
    .clock                         (clock),
    .io_in_ready                   (_EXU_io_in_ready),
    .io_in_valid                   (EXU_io_in_valid_REG),	// @[src/main/scala/npc/NPC.scala:29:33]
    .io_in_bits_aluASrc            (EXU_io_in_bits_r_aluASrc),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_aluBSrc            (EXU_io_in_bits_r_aluBSrc),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_jumpASrc           (EXU_io_in_bits_r_jumpASrc),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_jumpBSrc           (EXU_io_in_bits_r_jumpBSrc),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_ra1                (EXU_io_in_bits_r_ra1),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_wa                 (EXU_io_in_bits_r_wa),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_control_regWe      (EXU_io_in_bits_r_control_regWe),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_control_wbSrc      (EXU_io_in_bits_r_control_wbSrc),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_control_aluSel     (EXU_io_in_bits_r_control_aluSel),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_control_isArith    (EXU_io_in_bits_r_control_isArith),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_control_isLeft     (EXU_io_in_bits_r_control_isLeft),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_control_isUnsigned (EXU_io_in_bits_r_control_isUnsigned),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_control_isSub      (EXU_io_in_bits_r_control_isSub),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_control_csrSrc     (EXU_io_in_bits_r_control_csrSrc),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_control_csrCtr     (EXU_io_in_bits_r_control_csrCtr),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_control_brType     (EXU_io_in_bits_r_control_brType),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_control_pcSrc      (EXU_io_in_bits_r_control_pcSrc),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_control_memRen     (EXU_io_in_bits_r_control_memRen),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_control_memWen     (EXU_io_in_bits_r_control_memWen),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_control_memOp      (EXU_io_in_bits_r_control_memOp),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_pc                 (EXU_io_in_bits_r_pc),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_isEnd              (EXU_io_in_bits_r_isEnd),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_out_ready                  (_LSU_io_in_ready),	// @[src/main/scala/npc/NPC.scala:54:23]
    .io_out_valid                  (_EXU_io_out_valid),
    .io_out_bits_wa                (_EXU_io_out_bits_wa),
    .io_out_bits_alu_csr_Out       (_EXU_io_out_bits_alu_csr_Out),
    .io_out_bits_wdata             (_EXU_io_out_bits_wdata),
    .io_out_bits_control_regWe     (_EXU_io_out_bits_control_regWe),
    .io_out_bits_control_wbSrc     (_EXU_io_out_bits_control_wbSrc),
    .io_out_bits_control_memRen    (_EXU_io_out_bits_control_memRen),
    .io_out_bits_control_memWen    (_EXU_io_out_bits_control_memWen),
    .io_out_bits_control_memOp     (_EXU_io_out_bits_control_memOp),
    .io_out_bits_isEnd             (_EXU_io_out_bits_isEnd),
    .io_jump                       (_EXU_io_jump),
    .io_nextPC                     (_EXU_io_nextPC),
    .io_RegFileAccess_wa           (_EXU_io_RegFileAccess_wa),
    .io_RegFileAccess_we           (_EXU_io_RegFileAccess_we)
  );
  LSU LSU (	// @[src/main/scala/npc/NPC.scala:54:23]
    .clock                     (clock),
    .reset                     (reset),
    .io_in_ready               (_LSU_io_in_ready),
    .io_in_valid               (LSU_io_in_valid_REG),	// @[src/main/scala/npc/NPC.scala:29:33]
    .io_in_bits_wa             (LSU_io_in_bits_r_wa),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_alu_csr_Out    (LSU_io_in_bits_r_alu_csr_Out),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_wdata          (LSU_io_in_bits_r_wdata),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_control_regWe  (LSU_io_in_bits_r_control_regWe),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_control_wbSrc  (LSU_io_in_bits_r_control_wbSrc),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_control_memRen (LSU_io_in_bits_r_control_memRen),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_control_memWen (LSU_io_in_bits_r_control_memWen),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_control_memOp  (LSU_io_in_bits_r_control_memOp),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_isEnd          (LSU_io_in_bits_r_isEnd),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_out_ready              (_WBU_io_in_ready),	// @[src/main/scala/npc/NPC.scala:55:23]
    .io_out_valid              (_LSU_io_out_valid),
    .io_out_bits_wa            (_LSU_io_out_bits_wa),
    .io_out_bits_wd            (_LSU_io_out_bits_wd),
    .io_out_bits_control_regWe (_LSU_io_out_bits_control_regWe),
    .io_out_bits_isEnd         (_LSU_io_out_bits_isEnd),
    .io_master_awready         (_GEN & io_master_awready),	// @[src/main/scala/npc/axi4/AXI4.scala:452:16, :460:{65,81}, :461:29]
    .io_master_awvalid         (_LSU_io_master_awvalid),
    .io_master_awaddr          (_LSU_io_master_awaddr),
    .io_master_wready          (_GEN & io_master_wready),	// @[src/main/scala/npc/axi4/AXI4.scala:452:16, :460:{65,81}, :472:29]
    .io_master_wvalid          (_LSU_io_master_wvalid),
    .io_master_wdata           (_LSU_io_master_wdata),
    .io_master_wstrb           (_LSU_io_master_wstrb),
    .io_master_bready          (_LSU_io_master_bready),
    .io_master_bvalid          (_GEN_0),	// @[src/main/scala/npc/axi4/AXI4.scala:452:16, :460:81, :478:29]
    .io_master_bresp           (_GEN ? io_master_bresp : 2'h0),	// @[src/main/scala/npc/axi4/AXI4.scala:82:17, :452:16, :460:{65,81}, :479:29]
    .io_master_arready         (_GEN_1 & io_master_arready),	// @[src/main/scala/npc/axi4/AXI4.scala:452:16, :482:{63,79}, :483:29]
    .io_master_arvalid         (_LSU_io_master_arvalid),
    .io_master_araddr          (_LSU_io_master_araddr),
    .io_master_rready          (_LSU_io_master_rready),
    .io_master_rvalid          (_GEN_2),	// @[src/main/scala/npc/axi4/AXI4.scala:452:16, :482:79, :495:29]
    .io_master_rresp           (_GEN_1 ? io_master_rresp : 2'h0),	// @[src/main/scala/npc/axi4/AXI4.scala:82:17, :452:16, :482:{63,79}, :496:29]
    .io_master_rdata           (_GEN_1 ? io_master_rdata : 32'h0),	// @[src/main/scala/npc/NPC.scala:47:14, :51:23, :52:23, :53:23, :54:23, src/main/scala/npc/axi4/AXI4.scala:452:16, :482:{63,79}, :497:29]
    .io_RegFileAccess_wa       (_LSU_io_RegFileAccess_wa),
    .io_RegFileAccess_we       (_LSU_io_RegFileAccess_we)
  );
  WBU WBU (	// @[src/main/scala/npc/NPC.scala:55:23]
    .io_in_ready              (_WBU_io_in_ready),
    .io_in_valid              (WBU_io_in_valid_REG),	// @[src/main/scala/npc/NPC.scala:29:33]
    .io_in_bits_wa            (WBU_io_in_bits_r_wa),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_wd            (WBU_io_in_bits_r_wd),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_control_regWe (WBU_io_in_bits_r_control_regWe),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_in_bits_isEnd         (WBU_io_in_bits_r_isEnd),	// @[src/main/scala/npc/NPC.scala:27:33]
    .io_out_valid             (_WBU_io_out_valid),
    .io_out_bits_isEnd        (_WBU_io_out_bits_isEnd),
    .io_RegFileAccess_wa      (_WBU_io_RegFileAccess_wa),
    .io_RegFileAccess_we      (_WBU_io_RegFileAccess_we),
    .io_RegFileAccess_wd      (_WBU_io_RegFileAccess_wd)
  );
  RegFile RegFile (	// @[src/main/scala/npc/NPC.scala:56:23]
    .clock      (clock),
    .io_in_ra1  (_IDU_io_RegFileAccess_ra1),	// @[src/main/scala/npc/NPC.scala:52:23]
    .io_in_ra2  (_IDU_io_RegFileAccess_ra2),	// @[src/main/scala/npc/NPC.scala:52:23]
    .io_in_wa   (_WBU_io_RegFileAccess_wa),	// @[src/main/scala/npc/NPC.scala:55:23]
    .io_in_we   (_WBU_io_RegFileAccess_we),	// @[src/main/scala/npc/NPC.scala:55:23]
    .io_in_wd   (_WBU_io_RegFileAccess_wd),	// @[src/main/scala/npc/NPC.scala:55:23]
    .io_out_rd1 (_RegFile_io_out_rd1),
    .io_out_rd2 (_RegFile_io_out_rd2)
  );
  assign io_master_awvalid = ~_GEN_3 & _GEN & _LSU_io_master_awvalid;	// @[src/main/scala/npc/NPC.scala:45:7, :54:23, src/main/scala/npc/axi4/AXI4.scala:460:{65,81}, :462:29]
  assign io_master_awaddr = _GEN_4 ? 32'h0 : _LSU_io_master_awaddr;	// @[src/main/scala/npc/NPC.scala:45:7, :47:14, :51:23, :52:23, :53:23, :54:23, src/main/scala/npc/axi4/AXI4.scala:460:81, :466:30]
  assign io_master_wvalid = ~_GEN_3 & _GEN & _LSU_io_master_wvalid;	// @[src/main/scala/npc/NPC.scala:45:7, :54:23, src/main/scala/npc/axi4/AXI4.scala:460:{65,81}, :462:29, :473:29]
  assign io_master_wdata = _GEN_4 ? 32'h0 : _LSU_io_master_wdata;	// @[src/main/scala/npc/NPC.scala:45:7, :47:14, :51:23, :52:23, :53:23, :54:23, src/main/scala/npc/axi4/AXI4.scala:460:81, :466:30, :474:29]
  assign io_master_wstrb = _GEN_4 ? 4'h0 : _LSU_io_master_wstrb;	// @[src/main/scala/npc/NPC.scala:45:7, :47:14, :51:23, :52:23, :53:23, :54:23, :55:23, src/main/scala/npc/axi4/AXI4.scala:460:81, :466:30, :475:29]
  assign io_master_bready = ~_GEN_3 & _GEN & _LSU_io_master_bready;	// @[src/main/scala/npc/NPC.scala:45:7, :54:23, src/main/scala/npc/axi4/AXI4.scala:460:{65,81}, :462:29, :477:29]
  assign io_master_arvalid =
    _GEN_5 ? _ICache_io_master_arvalid : _GEN_1 & _LSU_io_master_arvalid;	// @[src/main/scala/npc/NPC.scala:45:7, :51:23, :54:23, src/main/scala/npc/axi4/AXI4.scala:455:17, :482:{63,79}, :484:29]
  assign io_master_araddr =
    _GEN_5 ? _ICache_io_master_araddr : _GEN_1 ? _LSU_io_master_araddr : 32'h0;	// @[src/main/scala/npc/NPC.scala:45:7, :47:14, :51:23, :52:23, :53:23, :54:23, src/main/scala/npc/axi4/AXI4.scala:455:17, :482:{63,79}, :488:30]
  assign io_master_rready =
    _GEN_5 ? _ICache_io_master_rready : _GEN_1 & _LSU_io_master_rready;	// @[src/main/scala/npc/NPC.scala:45:7, :51:23, :54:23, src/main/scala/npc/axi4/AXI4.scala:455:17, :482:{63,79}, :494:29]
  assign io_master_arlen = _GEN_5 ? _ICache_io_master_arlen : 8'h0;	// @[src/main/scala/npc/NPC.scala:45:7, :47:14, :51:23, :54:23, src/main/scala/npc/axi4/AXI4.scala:455:17, :482:{63,79}, :491:29]
endmodule

